-- AlterTable
ALTER TABLE `users` ADD COLUMN `bio` TEXT NULL,
    ADD COLUMN `company` VARCHAR(255) NULL,
    ADD COLUMN `github` VARCHAR(255) NULL,
    ADD COLUMN `joined_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `location` VARCHAR(255) NULL,
    ADD COLUMN `twitter` VARCHAR(255) NULL,
    ADD COLUMN `website` VARCHAR(255) NULL;
