stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - cd /home/yw/UltiCode
    - git fetch origin
    - git reset --hard origin/$CI_COMMIT_BRANCH
    - docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.ci.yml build
    - docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.ci.yml up -d
  only:
    - main
    - feat/gitlab-cicd
