const path = require('path')

const ROOT = __dirname
const BACKEND_CWD = path.join(ROOT, 'backend-spring')
const BACKEND_ENV_FILE = path.join(ROOT, '.env')

module.exports = {
  apps: [
    {
      name: 'ulticode-auth',
      cwd: BACKEND_CWD,
      script: 'mvn',
      args: '-f backend-auth/pom.xml spring-boot:run -Dspring-boot.run.profiles=dev',
      interpreter: 'none',
      env_file: BACKEND_ENV_FILE,
      env: {
        SERVER_PORT: '9101',
        DUBBO_REGISTRY_USERNAME: process.env.NACOS_USERNAME || '',
        DUBBO_REGISTRY_PASSWORD: process.env.NACOS_PASSWORD || '',
      },
      out_file: path.join(ROOT, 'logs', 'backend-auth.out.log'),
      error_file: path.join(ROOT, 'logs', 'backend-auth.err.log'),
      merge_logs: true,
      time: true,
      max_memory_restart: '1G',
    },
    {
      name: 'ulticode-admin',
      cwd: BACKEND_CWD,
      script: 'mvn',
      args: '-f backend-admin/pom.xml spring-boot:run -Dspring-boot.run.profiles=dev',
      interpreter: 'none',
      env_file: BACKEND_ENV_FILE,
      env: { SERVER_PORT: '9102' },
      out_file: path.join(ROOT, 'logs', 'backend-admin.out.log'),
      error_file: path.join(ROOT, 'logs', 'backend-admin.err.log'),
      merge_logs: true,
      time: true,
      max_memory_restart: '1G',
    },
    {
      name: 'ulticode-app',
      cwd: BACKEND_CWD,
      script: 'mvn',
      args: '-f backend-app/pom.xml spring-boot:run -Dspring-boot.run.profiles=dev',
      interpreter: 'none',
      env_file: BACKEND_ENV_FILE,
      env: {
        SERVER_PORT: '9103',
        DUBBO_REGISTRY_USERNAME: process.env.NACOS_USERNAME || '',
        DUBBO_REGISTRY_PASSWORD: process.env.NACOS_PASSWORD || '',
      },
      out_file: path.join(ROOT, 'logs', 'backend-app.out.log'),
      error_file: path.join(ROOT, 'logs', 'backend-app.err.log'),
      merge_logs: true,
      time: true,
      max_memory_restart: '1G',
    },
    {
      name: 'ulticode-9002',
      cwd: path.join(ROOT, 'console'),
      script: 'pnpm',
      args: 'dev',
      interpreter: 'none',
      env: { NODE_ENV: 'development', VITE_API_BASE_URL: '/api' },
      out_file: path.join(ROOT, 'logs', 'console.out.log'),
      error_file: path.join(ROOT, 'logs', 'console.err.log'),
      merge_logs: true,
      time: true,
      max_memory_restart: '512M',
    },
    {
      name: 'ulticode-9003',
      cwd: path.join(ROOT, 'management'),
      script: 'pnpm',
      args: 'dev',
      interpreter: 'none',
      env: { NODE_ENV: 'development', VITE_API_BASE_URL: '/api' },
      out_file: path.join(ROOT, 'logs', 'management.out.log'),
      error_file: path.join(ROOT, 'logs', 'management.err.log'),
      merge_logs: true,
      time: true,
      max_memory_restart: '512M',
    },
  ],
}
