module.exports = {
  apps: [
    {
      name: 'ulticode-9001',
      cwd: '/home/DavidHLP/UltiCode/backend-spring',
      script: 'mvn',
      args: 'spring-boot:run -Dspring-boot.run.profiles=dev',
      interpreter: 'none',
      env_file: '/home/DavidHLP/UltiCode/.env',
      env: { SERVER_PORT: '9001' },
      out_file: '/home/DavidHLP/UltiCode/logs/backend-spring.out.log',
      error_file: '/home/DavidHLP/UltiCode/logs/backend-spring.err.log',
      merge_logs: true,
      time: true,
      max_memory_restart: '1G',
    },
    {
      name: 'ulticode-9002',
      cwd: '/home/DavidHLP/UltiCode/console',
      script: 'pnpm',
      args: 'dev',
      interpreter: 'none',
      env: { NODE_ENV: 'development' },
      out_file: '/home/DavidHLP/UltiCode/logs/console.out.log',
      error_file: '/home/DavidHLP/UltiCode/logs/console.err.log',
      merge_logs: true,
      time: true,
      max_memory_restart: '512M',
    },
    {
      name: 'ulticode-9003',
      cwd: '/home/DavidHLP/UltiCode/management',
      script: 'pnpm',
      args: 'dev',
      interpreter: 'none',
      env: { NODE_ENV: 'development' },
      out_file: '/home/DavidHLP/UltiCode/logs/management.out.log',
      error_file: '/home/DavidHLP/UltiCode/logs/management.err.log',
      merge_logs: true,
      time: true,
      max_memory_restart: '512M',
    },
  ],
}
