packages:
  - "."
overrides:
  dompurify: 3.4.5
  lodash-es: 4.18.1
  protocol-buffers-schema: 3.6.1
ignoredBuiltDependencies:
  - esbuild
  - maplibre-gl
  - msw
  - vue-demi
allowBuilds:
  esbuild: true
  maplibre-gl: true
  vue-demi: true
