package com.ulticode.modules.contest.entity;

import com.baomidou.mybatisplus.annotation.*;
import com.ulticode.modules.contest.entity.enums.ContestParticipantStatus;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Contest participant entity.
 *
 * <p>The {@code status} column is persisted as a {@code VARCHAR} (see
 * {@code V20260602_120000__Create_All_Tables.sql}). All Java code that
 * compares or assigns the column goes through
 * {@link #getStatusAsEnum()} / {@link #setStatusEnum(ContestParticipantStatus)}
 * so the durable wire value has a single source of truth
 * ({@link ContestParticipantStatus#wireValue()}).
 */
@Data
@TableName("contest_participants")
public class ContestParticipant {

    @TableId(type = IdType.ASSIGN_UUID)
    private String id;

    private String contestId;

    private String userId;

    /**
     * Raw persisted status. Generated by Lombok as
     * {@code setStatus(String)} so MyBatis-Plus reads the column as-is.
     * Callers that need to assign the status should use
     * {@link #setStatusEnum(ContestParticipantStatus)} (or build a new
     * instance with the typed setter) so the canonical wire value is
     * the only path the column takes.
     */
    private String status;

    private LocalDateTime registeredAt;

    private LocalDateTime startedAt;

    private LocalDateTime finishedAt;

    private LocalDateTime checkedInAt;

    private Boolean isVirtual;

    private Integer finalRank;

    private Integer totalPenalty;

    private Integer totalScore;

    private Integer totalTime;

    private Integer totalAttempts;

    private Integer attemptCount;

    private Integer lastSolveTime;

    private String virtualSessionId;

    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createdAt;

    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updatedAt;

    /**
     * Type-safe reader for the persisted status. Returns {@code null} when
     * the row is missing a status (legacy) so callers can distinguish
     * "no status" from "unknown status".
     */
    public ContestParticipantStatus getStatusAsEnum() {
        return ContestParticipantStatus.fromWire(status);
    }

    /**
     * Type-safe writer for the persisted status. Persists the canonical
     * wire value so the column always matches the SQL guard in the
     * mapper's conditional UPDATEs. The setter name avoids clashing with
     * the Lombok-generated {@code setStatus(String)} so MyBatis-Plus
     * reads still work.
     */
    public void setStatusEnum(ContestParticipantStatus newStatus) {
        this.status = newStatus == null ? null : newStatus.wireValue();
    }

    /**
     * Convenience: {@code true} when the persisted status is
     * {@link ContestParticipantStatus#STARTED}. Use this in place of
     * {@code "STARTED".equals(getStatus())} to avoid the string-literal
     * spread.
     */
    public boolean isStarted() {
        return ContestParticipantStatus.STARTED.wireValue().equals(status);
    }

    /**
     * Convenience: {@code true} when the persisted status is
     * {@link ContestParticipantStatus#FINISHED}.
     */
    public boolean isFinished() {
        return ContestParticipantStatus.FINISHED.wireValue().equals(status);
    }

    /**
     * Convenience: {@code true} when the persisted status is
     * {@link ContestParticipantStatus#REGISTERED}.
     */
    public boolean isRegistered() {
        return ContestParticipantStatus.REGISTERED.wireValue().equals(status);
    }
}
