-- ============================================================
-- V20260601000000__Seed_Solutions_Test_Data.sql
-- 为 solutions 页面设计合理的测试数据
-- 注意：使用 INSERT IGNORE 避免重复插入
-- ============================================================

-- ---------------------------------------------------
-- 1. 先确保有足够的测试用户（user_id 需要引用）
-- ---------------------------------------------------
INSERT IGNORE INTO users (id, username, name, email, avatar, password, bio, role, is_active, is_banned, is_deleted) VALUES
('user-alice-001', 'alice_coder', 'Alice Johnson', 'alice@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice', '$2a$10$dummy', '算法爱好者，专注动态规划', 'USER', 1, 0, 0),
('user-bob-002', 'bob_dev', 'Bob Smith', 'bob@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=bob', '$2a$10$dummy', 'Java / Python 双修，热爱系统设计', 'USER', 1, 0, 0),
('user-carol-003', 'carol_wu', 'Carol Wu', 'carol@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=carol', '$2a$10$dummy', '竞赛党，ACMer', 'USER', 1, 0, 0),
('user-david-004', 'david_chen', 'David Chen', 'david@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=david', '$2a$10$dummy', '前端转全栈，喜欢写题解', 'USER', 1, 0, 0),
('user-eva-005', 'eva_zhang', 'Eva Zhang', 'eva@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=eva', '$2a$10$dummy', 'Python 达人，AI 初学者', 'USER', 1, 0, 0),
('user-frank-006', 'frank_lee', 'Frank Lee', 'frank@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=frank', '$2a$10$dummy', 'C++ 手写高性能代码', 'USER', 1, 0, 0);

-- ---------------------------------------------------
-- 2. 插入 solutions 测试数据
-- 注意：problems 表只有 id=1 存在，其他 problem_id 使用 1
-- ---------------------------------------------------
INSERT IGNORE INTO solutions (id, problem_id, user_id, title, content, summary, language, tags, views, likes, dislikes, comment_count, is_published, published_at, published_by, is_flagged, flagged_reason, flagged_at, is_deleted, is_pinned, created_at, updated_at) VALUES

-- 正常发布的 solution（多种语言）
('sol-001', 1, 'user-alice-001', 'Two Sum 双指针解法', '# Two Sum 双指针解法\n\n## 思路\n\n使用双指针从数组两端向中间收缩，找到目标和。\n\n## 代码\n\n```python\ndef two_sum(nums, target):\n    left, right = 0, len(nums) - 1\n    while left < right:\n        current_sum = nums[left] + nums[right]\n        if current_sum == target:\n            return [left, right]\n        elif current_sum < target:\n            left += 1\n        else:\n            right -= 1\n    return []\n```\n\n## 复杂度\n- 时间：O(n)\n- 空间：O(1)\n\n## 注意事项\n双指针只适用于有序数组，若无序需先排序。', '详细的 Python 双指针解法，包含思路、代码、复杂度分析和注意事项', 'python', '["双指针", "数组"]', 1250, 45, 2, 3, 1, NOW(), 'user-alice-001', 0, NULL, NULL, 0, 0, NOW(), NOW()),

('sol-002', 1, 'user-bob-002', 'Java 哈希表解法', 'package com.ulticode.solutions;\n\nimport java.util.*;\n\npublic class TwoSum {\n    public int[] solution(int[] nums, int target) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int complement = target - nums[i];\n            if (map.containsKey(complement)) {\n                return new int[]{map.get(complement), i};\n            }\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}', 'Java HashMap 解法，简洁高效', 'java', '["哈希表"]', 890, 32, 1, 2, 1, NOW(), 'user-bob-002', 0, NULL, NULL, 0, 0, NOW(), NOW()),

('sol-003', 1, 'user-carol-003', '链表演算法详细图解', '# 链表演算法\n\n## 问题描述\n\n给定两个非空链表，表示两个非负整数。每位数字都是反向存储的，每个节点包含一个数字。将这两个数相加返回一个新的链表。\n\n## 图解\n\n假设输入：\n- L1: 2 -> 4 -> 3\n- L2: 5 -> 6 -> 4\n\n结果： 7 -> 0 -> 8\n\n## 代码实现\n\n```python\nclass ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef add_two_numbers(l1, l2):\n    dummy = ListNode(0)\n    current, carry = dummy, 0\n    \n    while l1 or l2 or carry:\n        val1 = l1.val if l1 else 0\n        val2 = l2.val if l2 else 0\n        \n        total = val1 + val2 + carry\n        carry = total // 10\n        current.next = ListNode(total % 10)\n        \n        current = current.next\n        l1 = l1.next if l1 else None\n        l2 = l2.next if l2 else None\n    \n    return dummy.next\n```\n\n## 复杂度\n时间 O(max(m,n))，空间 O(max(m,n))', '详细的链表演算法，包含图解、Python 实现和复杂度分析', 'python', '["链表", "数学"]', 2100, 78, 5, 8, 1, NOW(), 'user-carol-003', 0, NULL, NULL, 0, 0, NOW(), NOW()),

('sol-004', 1, 'user-david-004', '滑动窗口求最长无重复子串', '# 滑动窗口解法\n\n```javascript\nfunction lengthOfLongestSubstring(s) {\n    const charSet = new Set();\n    let left = 0, result = 0;\n    \n    for (let right = 0; right < s.length; right++) {\n        while (charSet.has(s[right])) {\n            charSet.delete(s[left]);\n            left++;\n        }\n        charSet.add(s[right]);\n        result = Math.max(result, right - left + 1);\n    }\n    return result;\n}\n```\n\n关键点：使用 Set 存储窗口内的字符，遇到重复字符时收缩左边界。', 'JavaScript 滑动窗口解法，简洁易懂', 'javascript', '["滑动窗口", "哈希表", "字符串"]', 567, 21, 0, 1, 1, NOW(), 'user-david-004', 0, NULL, NULL, 0, 0, NOW(), NOW()),

('sol-005', 1, 'user-frank-006', '中位数二分查找 - 详解', '// C++ 二分查找解法\n// 时间复杂度 O(log(m+n))\n\nclass Solution {\npublic:\n    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n        int m = nums1.size(), n = nums2.size();\n        if (m > n) return findMedianSortedArrays(nums2, nums1);\n        \n        int left = 0, right = m;\n        int maxLeft = 0, minRight = 0;\n        \n        while (left <= right) {\n            int i = (left + right) / 2;\n            int j = (m + n + 1) / 2 - i;\n            \n            int nums1Left = (i == 0) ? INT_MIN : nums1[i-1];\n            int nums1Right = (i == m) ? INT_MAX : nums1[i];\n            int nums2Left = (j == 0) ? INT_MIN : nums2[j-1];\n            int nums2Right = (j == n) ? INT_MAX : nums2[j];\n            \n            if (nums1Left <= nums2Right && nums2Left <= nums1Right) {\n                if ((m + n) % 2 == 0) {\n                    return (max(nums1Left, nums2Left) + min(nums1Right, nums2Right)) / 2.0;\n                } else {\n                    return max(nums1Left, nums2Left);\n                }\n            } else if (nums1Left > nums2Right) {\n                right = i - 1;\n            } else {\n                left = i + 1;\n            }\n        }\n        return 0.0;\n    }\n};', 'C++ 二分查找，详细注释，适合学习', 'cpp', '["二分查找", "分治"]', 320, 15, 1, 0, 1, NOW(), 'user-frank-006', 0, NULL, NULL, 0, 0, NOW(), NOW()),

-- 被标记的 solution（待审核）
('sol-006', 1, 'user-eva-005', 'Two Sum 暴力枚举', '// 暴力解法 - 不推荐\n// 时间复杂度 O(n^2)\n\nclass Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        for (int i = 0; i < nums.size(); i++) {\n            for (int j = i + 1; j < nums.size(); j++) {\n                if (nums[i] + nums[j] == target) {\n                    return {i, j};\n                }\n            }\n        }\n        return {};\n    }\n};', '暴力解法，仅作为对比参考', 'cpp', '["暴力枚举"]', 156, 3, 12, 1, 1, NOW(), 'user-eva-005', 1, '低效解法，无实际参考价值，且未提供优化思路', NOW(), 0, 0, NOW(), NOW()),

('sol-007', 1, 'user-eva-005', '链表反转后相加', '// 错误的实现 - 不要使用\n// 这个解法有 bug，请参考 sol-003 的正确版本', '错误实现，仅供警示', 'python', '["链表"]', 89, 1, 8, 0, 1, NOW(), 'user-eva-005', 1, '代码存在边界条件 bug，运行时会出错', NOW(), 0, 0, NOW(), NOW()),

-- 未发布的 solution（草稿）
('sol-008', 1, 'user-alice-001', '二分查找初步思路', '# 待完成\n\n还在思考如何处理边界情况...', '还在整理思路', 'python', '["二分"]', 12, 0, 0, 0, 0, NULL, NULL, 0, NULL, NULL, 0, 0, NOW(), NOW()),

-- 已删除的 solution（回收站）
('sol-009', 1, 'user-bob-002', '滑动窗口旧版', '// 旧版本，已被新方案取代', '旧版，待删除', 'javascript', '["滑动窗口"]', 45, 2, 0, 0, 0, NULL, NULL, 0, NULL, NULL, 1, 0, NOW(), NOW()),

-- 置顶的 solution（优质内容）
('sol-010', 1, 'user-carol-003', '【精选】Two Sum 最优解法汇总', '# 精选题解 - Two Sum\n\n本文整理了三种最优解法：\n\n1. **哈希表** - O(n) 时间\n2. **双指针** - O(nlogn) 时间（需排序）\n3. **暴力枚举** - O(n²) 不推荐\n\n## 哈希表解法（推荐）\n\n```python\ndef two_sum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[num] = i\n    return []\n```\n\n## 为什么哈希表最快？\n\n哈希表查找 O(1)，整体 O(n)。空间换时间的经典案例。', '精选优质题解，包含多种解法对比', 'python', '["哈希表", "双指针", "精选"]', 4500, 156, 8, 25, 1, NOW(), 'user-carol-003', 0, NULL, NULL, 0, 1, NOW(), NOW()),

-- 其他语言的 solution
('sol-011', 1, 'user-frank-006', '动态规划详解', '# 最长回文子串 - 动态规划\n\n```python\ndef longest_palindrome(s: str) -> str:\n    n = len(s)\n    if n < 2:\n        return s\n    \n    start, max_len = 0, 1\n    dp = [[False] * n for _ in range(n)]\n    \n    for i in range(n):\n        dp[i][i] = True\n    \n    for length in range(2, n + 1):\n        for i in range(n - length + 1):\n            j = i + length - 1\n            if length == 2:\n                dp[i][j] = (s[i] == s[j])\n            else:\n                dp[i][j] = (s[i] == s[j] and dp[i+1][j-1])\n            \n            if dp[i][j] and length > max_len:\n                start, max_len = i, length\n    \n    return s[start:start + max_len]\n```', '动态规划方法，详细注释', 'python', '["动态规划", "字符串"]', 780, 34, 2, 5, 1, NOW(), 'user-frank-006', 0, NULL, NULL, 0, 0, NOW(), NOW()),

('sol-012', 1, 'user-david-004', 'Z字形变换 Go 实现', 'package main\n\nimport (\n    "strings"\n)\n\nfunc convert(s string, numRows int) string {\n    if numRows == 1 {\n        return s\n    }\n    \n    rows := make([]string, numRows)\n    currentRow := 0\n    goingDown := false\n    \n    for _, c := range s {\n        rows[currentRow] += string(c)\n        if currentRow == 0 || currentRow == numRows-1 {\n            goingDown = !goingDown\n        }\n        if goingDown {\n            currentRow++\n        } else {\n            currentRow--\n        }\n    }\n    \n    return strings.Join(rows, "")\n}', 'Go 语言实现 Z 字形变换', 'go', '["字符串"]', 234, 12, 0, 2, 1, NOW(), 'user-david-004', 0, NULL, NULL, 0, 0, NOW(), NOW()),

('sol-013', 1, 'user-alice-001', '整数反转 C 语言版', '// C 语言版整数反转\n// 注意溢出检测\n\n#include <limits.h>\n\nint reverse(int x) {\n    int rev = 0;\n    while (x != 0) {\n        int pop = x % 10;\n        x /= 10;\n        \n        if (rev > INT_MAX/10 || (rev == INT_MAX/10 && pop > 7)) return 0;\n        if (rev < INT_MIN/10 || (rev == INT_MIN/10 && pop < -8)) return 0;\n        \n        rev = rev * 10 + pop;\n    }\n    return rev;\n}', 'C 语言版，注意溢出处理', 'c', '["数学"]', 189, 8, 1, 1, 1, NOW(), 'user-alice-001', 0, NULL, NULL, 0, 0, NOW(), NOW()),

('sol-014', 1, 'user-frank-006', '链表演算法 Go 版本', 'package solution\n\ntype ListNode struct {\n    Val int\n    Next *ListNode\n}\n\nfunc addTwoNumbers(l1, l2 *ListNode) *ListNode {\n    head := &ListNode{}\n    current, carry := head, 0\n    \n    for l1 != nil || l2 != nil || carry != 0 {\n        val := carry\n        if l1 != nil {\n            val += l1.Val\n            l1 = l1.Next\n        }\n        if l2 != nil {\n            val += l2.Val\n            l2 = l2.Next\n        }\n        \n        carry = val / 10\n        current.Next = &ListNode{Val: val % 10}\n        current = current.Next\n    }\n    \n    return head.Next\n}', 'Go 语言版链表演算法', 'go', '["链表", "数学"]', 445, 18, 1, 3, 1, NOW(), 'user-frank-006', 0, NULL, NULL, 0, 0, NOW(), NOW()),

('sol-015', 1, 'user-carol-003', '滑动窗口 Rust 实现', 'fn length_of_longest_substring(s: String) -> i32 {\n    let mut char_set: std::collections::HashSet<char> = std::collections::HashSet::new();\n    let mut left = 0;\n    let mut result = 0;\n    \n    for (right, c) in s.char_indices() {\n        while char_set.contains(&c) {\n            char_set.remove(&s.chars().nth(left).unwrap());\n            left += 1;\n        }\n        char_set.insert(c);\n        result = result.max(right - left + 1);\n    }\n    \n    result as i32\n}', 'Rust 实现滑动窗口', 'rust', '["滑动窗口", "哈希表"]', 156, 9, 0, 1, 1, NOW(), 'user-carol-003', 0, NULL, NULL, 0, 0, NOW(), NOW());