-- V3 (deprecated): Insert Test Data
-- ------------------------------------------------------------
-- ⚠️  本文件已被按业务拆分为以下 6 个独立 migration,
--    修改测试数据时, 请直接编辑对应的新文件, 不再编辑本占位文件。
--
--    V20260603_120000  Seed_Problems_Test_Data            (problems + problem_details)
--    V20260603_120100  Seed_Audit_Logs_Test_Data          (audit_logs)
--    V20260603_120200  Seed_Problem_Lists_Test_Data       (problem_lists + relations)
--    V20260603_120300  Seed_Users_And_Permissions         (users + role_permissions)
--    V20260603_120400  Seed_Solutions_Test_Data           (solutions)
--    V20260603_120500  Fix_Forum_User_References          (forum author_id / user_id 修复)
--
-- 历史:  原文件 V20260602_120200 集中存放了 problems / audit_logs / problem_lists /
--        users / role_permissions / solutions / forum 修复 7 类测试数据 (共 375 行),
--        后续修改时频繁跨业务相互影响。 2026-06-03 重构拆分。
--
-- 字符集说明 (保留供历史参考):
--   1. 容器化 MySQL 默认 character_set_client=latin1, 直接 docker exec ... 写中文
--      会双重 UTF-8 编码。
--   2. 正确做法: docker exec ... mysql --default-character-set=utf8mb4
--   3. 后端 JDBC URL 已包含 useUnicode=true&characterEncoding=UTF-8,
--      Flyway 走应用连接字符正常。
-- ------------------------------------------------------------
-- 本占位 migration 不再执行任何 DML/DDL, 仅保留历史记录。
