-- Migration:
--   V20260530160000__Grant_All_Permissions_To_SuperAdmin.sql
--
-- Purpose:
--   Grant all system permissions to SUPER_ADMIN role for full administrative access.
--
-- Risk:
--   Low. INSERT ON DUPLICATE KEY UPDATE is idempotent. Only adds permission records.
--
-- Compatibility:
--   Compatible. Permissions are additive and optional for existing users.
--
-- Rollback:
--   DELETE FROM role_permissions WHERE role = 'SUPER_ADMIN';
--
-- Verify:
--   SELECT COUNT(*) FROM role_permissions WHERE role = 'SUPER_ADMIN';
--   Should return 139+ rows

-- Grant all permissions to SUPER_ADMIN role
-- This ensures the admin user automatically inherits all permissions through their role

INSERT INTO role_permissions (id, role, action, resource, created_at) VALUES
-- USER management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'USER', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'USER', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'USER', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'USER', NOW()),
(UUID(), 'SUPER_ADMIN', 'MANAGE_USERS', 'USER', NOW()),
(UUID(), 'SUPER_ADMIN', 'MANAGE_PERMISSIONS', 'USER', NOW()),

-- PROBLEM management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'PROBLEM', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'PROBLEM', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'PROBLEM', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'PROBLEM', NOW()),

-- SUBMISSION management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'SUBMISSION', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'SUBMISSION', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'SUBMISSION', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'SUBMISSION', NOW()),

-- CONTEST management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'CONTEST', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'CONTEST', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'CONTEST', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'CONTEST', NOW()),

-- FORUM_POST management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'FORUM_POST', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'FORUM_POST', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'FORUM_POST', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'FORUM_POST', NOW()),
(UUID(), 'SUPER_ADMIN', 'PUBLISH', 'FORUM_POST', NOW()),
(UUID(), 'SUPER_ADMIN', 'MODERATE', 'FORUM_POST', NOW()),

-- FORUM_COMMENT management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'FORUM_COMMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'FORUM_COMMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'FORUM_COMMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'FORUM_COMMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'MODERATE', 'FORUM_COMMENT', NOW()),

-- SOLUTION management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'SOLUTION', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'SOLUTION', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'SOLUTION', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'SOLUTION', NOW()),

-- SOLUTION_COMMENT management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'SOLUTION_COMMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'SOLUTION_COMMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'SOLUTION_COMMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'SOLUTION_COMMENT', NOW()),

-- PROBLEM_LIST management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'PROBLEM_LIST', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'PROBLEM_LIST', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'PROBLEM_LIST', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'PROBLEM_LIST', NOW()),

-- ROLE management
(UUID(), 'SUPER_ADMIN', 'READ', 'ROLE', NOW()),
(UUID(), 'SUPER_ADMIN', 'MANAGE_PERMISSIONS', 'ROLE', NOW()),

-- PERMISSION management
(UUID(), 'SUPER_ADMIN', 'READ', 'PERMISSION', NOW()),
(UUID(), 'SUPER_ADMIN', 'MANAGE_PERMISSIONS', 'PERMISSION', NOW()),

-- NOTIFICATION management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'NOTIFICATION', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'NOTIFICATION', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'NOTIFICATION', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'NOTIFICATION', NOW()),

-- ACHIEVEMENT management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'ACHIEVEMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'ACHIEVEMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'ACHIEVEMENT', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'ACHIEVEMENT', NOW()),

-- BILLING management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'BILLING', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'BILLING', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'BILLING', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'BILLING', NOW()),

-- SYSTEM management
(UUID(), 'SUPER_ADMIN', 'READ', 'SYSTEM', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'SYSTEM', NOW()),

-- DASHBOARD access
(UUID(), 'SUPER_ADMIN', 'READ', 'DASHBOARD', NOW()),

-- MODERATION management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'MODERATION', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'MODERATION', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'MODERATION', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'MODERATION', NOW()),
(UUID(), 'SUPER_ADMIN', 'MODERATE', 'MODERATION', NOW()),

-- BACKUP management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'BACKUP', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'BACKUP', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'BACKUP', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'BACKUP', NOW()),

-- AUDIT_LOG management
(UUID(), 'SUPER_ADMIN', 'READ', 'AUDIT_LOG', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'AUDIT_LOG', NOW()),

-- REPORT management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'REPORT', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'REPORT', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'REPORT', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'REPORT', NOW()),

-- SEARCH access
(UUID(), 'SUPER_ADMIN', 'READ', 'SEARCH', NOW()),

-- TAG management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'TAG', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'TAG', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'TAG', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'TAG', NOW()),

-- BOOKMARK management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'BOOKMARK', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'BOOKMARK', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'BOOKMARK', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'BOOKMARK', NOW()),

-- FOLLOW management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'FOLLOW', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'FOLLOW', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'FOLLOW', NOW()),

-- VOTE management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'VOTE', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'VOTE', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'VOTE', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'VOTE', NOW()),

-- EMAIL management
(UUID(), 'SUPER_ADMIN', 'CREATE', 'EMAIL', NOW()),
(UUID(), 'SUPER_ADMIN', 'READ', 'EMAIL', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'EMAIL', NOW()),
(UUID(), 'SUPER_ADMIN', 'DELETE', 'EMAIL', NOW()),

-- QUEUE management
(UUID(), 'SUPER_ADMIN', 'READ', 'QUEUE', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'QUEUE', NOW()),

-- RECOMMENDATION management
(UUID(), 'SUPER_ADMIN', 'READ', 'RECOMMENDATION', NOW()),
(UUID(), 'SUPER_ADMIN', 'UPDATE', 'RECOMMENDATION', NOW())

ON DUPLICATE KEY UPDATE created_at = NOW();