-- AlterTable
ALTER TABLE `role_permissions` MODIFY `resource` ENUM('USER', 'PROBLEM', 'CONTEST', 'SOLUTION', 'FORUM_POST', 'FORUM_COMMENT', 'SYSTEM', 'PROBLEM_LIST') NOT NULL;

-- AlterTable
ALTER TABLE `user_permissions` MODIFY `resource` ENUM('USER', 'PROBLEM', 'CONTEST', 'SOLUTION', 'FORUM_POST', 'FORUM_COMMENT', 'SYSTEM', 'PROBLEM_LIST') NOT NULL;
