@echo off
REM PitStop — UltiCode — Start Script
REM Generated by pitstop export

setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
set "PID_DIR=./logs\\.pids"
set "LOG_DIR=./logs"

if not exist "%PID_DIR%" mkdir "%PID_DIR%"
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

echo Starting UltiCode...
echo.
REM --- backend-spring ---
echo   Starting [backend-spring]...
cd /d "%SCRIPT_DIR%\\C:\admin\Code\Project\OJ\UltiCode\backend-spring"
start /b cmd /c "mvn spring-boot:run" > "%LOG_DIR%\\backend-spring.log" 2>&1
echo !ERRORLEVEL! > "%PID_DIR%\\backend-spring.pid"
echo     PID: !ERRORLEVEL!

REM --- console ---
echo   Starting [console]...
cd /d "%SCRIPT_DIR%\\C:\admin\Code\Project\OJ\UltiCode\console"
start /b cmd /c "pnpm dev" > "%LOG_DIR%\\console.log" 2>&1
echo !ERRORLEVEL! > "%PID_DIR%\\console.pid"
echo     PID: !ERRORLEVEL!

REM --- management ---
echo   Starting [management]...
cd /d "%SCRIPT_DIR%\\C:\admin\Code\Project\OJ\UltiCode\management"
start /b cmd /c "pnpm dev" > "%LOG_DIR%\\management.log" 2>&1
echo !ERRORLEVEL! > "%PID_DIR%\\management.pid"
echo     PID: !ERRORLEVEL!


echo.
echo All services started.
echo Logs: %LOG_DIR%
echo Run stop.bat to stop all services.
