#!/bin/bash
# PitStop — UltiCode — Start Script
# Generated by pitstop export

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PID_DIR="./logs/.pids"
LOG_DIR="./logs"

mkdir -p "$PID_DIR" "$LOG_DIR"

echo "🏁 Starting UltiCode..."
echo ""
# --- services ---
echo "  Starting [services]..."
cd "$SCRIPT_DIR/C:\admin\Code\Project\OJ\UltiCode\services"
nohup mvn spring-boot:run > "$LOG_DIR/services.log" 2>&1 &
echo $! > "$PID_DIR/services.pid"
echo "    PID: $(cat "$PID_DIR/services.pid") → $LOG_DIR/services.log"

# --- console ---
echo "  Starting [console]..."
cd "$SCRIPT_DIR/C:\admin\Code\Project\OJ\UltiCode\console"
nohup pnpm dev > "$LOG_DIR/console.log" 2>&1 &
echo $! > "$PID_DIR/console.pid"
echo "    PID: $(cat "$PID_DIR/console.pid") → $LOG_DIR/console.log"

# --- management ---
echo "  Starting [management]..."
cd "$SCRIPT_DIR/C:\admin\Code\Project\OJ\UltiCode\management"
nohup pnpm dev > "$LOG_DIR/management.log" 2>&1 &
echo $! > "$PID_DIR/management.pid"
echo "    PID: $(cat "$PID_DIR/management.pid") → $LOG_DIR/management.log"


echo ""
echo "All services started."
echo "Logs: $LOG_DIR"
echo "Run ./stop.sh to stop all services."
