@echo off
REM PitStop — UltiCode — Start Script
REM Generated by pitstop export

setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
pushd "%SCRIPT_DIR%"
set "PID_DIR=.\logs\.pids"
set "LOG_DIR=.\logs"

if not exist "%PID_DIR%" mkdir "%PID_DIR%"
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

echo Starting UltiCode...
echo.
call :start_service services services "mvn spring-boot:run"
if errorlevel 1 goto :failed
call :start_service console apps\console "pnpm dev"
if errorlevel 1 goto :failed
call :start_service management apps\management "pnpm dev"
if errorlevel 1 goto :failed

echo.
echo All services started.
echo Logs: %LOG_DIR%
echo Run stop.bat to stop all services.
popd
exit /b 0

:failed
echo Failed to start all services. See the logs under %LOG_DIR%.
popd
exit /b 1

:start_service
set "SERVICE_NAME=%~1"
set "SERVICE_DIR=%~2"
set "SERVICE_COMMAND=%~3"
set "SERVICE_PID="
echo   Starting [!SERVICE_NAME!]...
for /f "usebackq delims=" %%p in (`powershell -NoProfile -Command "$p = Start-Process -FilePath 'cmd.exe' -ArgumentList '/d','/c','%SERVICE_COMMAND%' -WorkingDirectory '%SCRIPT_DIR%%SERVICE_DIR%' -RedirectStandardOutput '%SCRIPT_DIR%%LOG_DIR%\%SERVICE_NAME%.log' -RedirectStandardError '%SCRIPT_DIR%%LOG_DIR%\%SERVICE_NAME%.error.log' -WindowStyle Hidden -PassThru; $p.Id"`) do set "SERVICE_PID=%%p"
if not defined SERVICE_PID (
  echo     Failed to obtain a process ID for !SERVICE_NAME!.
  exit /b 1
)
>"%PID_DIR%\%SERVICE_NAME%.pid" echo !SERVICE_PID!
echo     PID: !SERVICE_PID!
exit /b 0
