#!/bin/bash
# PitStop — UltiCode — Start Script
# Generated by pitstop export

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"
PID_DIR="./logs/.pids"
LOG_DIR="./logs"

mkdir -p "$PID_DIR" "$LOG_DIR"

echo "🏁 Starting UltiCode..."
echo ""

start_service() {
  local name="$1"
  local workdir="$2"
  shift 2

  (
    cd "$SCRIPT_DIR"
    nohup bash -c 'cd "$1" && shift && exec "$@"' -- "$workdir" "$@" \
      > "$LOG_DIR/$name.log" 2>&1 &
    echo $! > "$PID_DIR/$name.pid"
  )
  echo "    PID: $(cat "$PID_DIR/$name.pid") → $LOG_DIR/$name.log"
}

# --- services ---
echo "  Starting [services]..."
start_service services ./services mvn spring-boot:run

# --- console ---
echo "  Starting [console]..."
start_service console ./apps/console pnpm dev

# --- management ---
echo "  Starting [management]..."
start_service management ./apps/management pnpm dev

echo ""
echo "All services started."
echo "Logs: $LOG_DIR"
echo "Run ./stop.sh to stop all services."
