#!/bin/bash
# PitStop — UltiCode — Stop Script
# Generated by pitstop export

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PID_DIR="./logs/.pids"

echo "Stopping UltiCode..."

if [ ! -d "$PID_DIR" ]; then
  echo "No PID directory found. Services may not be running."
  exit 0
fi

stopped=0
for pidfile in "$PID_DIR"/*.pid; do
  [ -f "$pidfile" ] || continue
  name=$(basename "$pidfile" .pid)
  pid=$(cat "$pidfile")

  if kill -0 "$pid" 2>/dev/null; then
    echo "  Stopping [$name] (PID: $pid)..."
    kill "$pid" 2>/dev/null || true
    # Wait up to 10 seconds.
    for i in $(seq 1 20); do
      kill -0 "$pid" 2>/dev/null || break
      sleep 0.5
    done
    # Force kill if still alive.
    if kill -0 "$pid" 2>/dev/null; then
      echo "    Force killing [$name]..."
      kill -9 "$pid" 2>/dev/null || true
    fi
    stopped=$((stopped + 1))
  else
    echo "  [$name] (PID: $pid) already stopped."
  fi
  rm -f "$pidfile"
done

rmdir "$PID_DIR" 2>/dev/null || true

echo ""
echo "Stopped $stopped service(s)."
