@echo off
REM PitStop — UltiCode — Stop Script
REM Generated by pitstop export

setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
pushd "%SCRIPT_DIR%"
set "PID_DIR=.\logs\.pids"

echo Stopping UltiCode...

if not exist "%PID_DIR%" (
  echo No PID directory found. Services may not be running.
  popd
  exit /b 0
)

set stopped=0
for %%f in ("%PID_DIR%\*.pid") do (
  set "name=%%~nf"
  set /p pid=<"%%f"

  echo   Stopping [!name!] (PID: !pid!)...
  taskkill /PID !pid! /T >nul 2>&1
  if !ERRORLEVEL! equ 0 (
    set /a stopped+=1
  ) else (
    echo     Already stopped.
  )
  del "%%f" >nul 2>&1
)

echo.
echo Stopped !stopped! service(s).
popd
