SET FOREIGN_KEY_CHECKS=0;
-- UltiCode Migration: V104__add_appeal_rejected_to_moderation_enum
-- Adds APPEAL_REJECTED to moderation action and resolution enums

ALTER TABLE `moderation_actions`
  MODIFY COLUMN `action` enum('DELETED','HIDDEN','RESTORED','WARNED','TEMP_BANNED','PERM_BANNED','DISMISSED','RESOLVED','APPEAL_PENDING','APPEAL_APPROVED','APPEAL_REJECTED') COLLATE utf8mb4_unicode_ci NOT NULL;

ALTER TABLE `moderation_queue`
  MODIFY COLUMN `resolution` enum('DELETED','HIDDEN','RESTORED','WARNED','TEMP_BANNED','PERM_BANNED','DISMISSED','RESOLVED','APPEAL_PENDING','APPEAL_APPROVED','APPEAL_REJECTED') COLLATE utf8mb4_unicode_ci DEFAULT NULL;

SET FOREIGN_KEY_CHECKS=1;
