SET FOREIGN_KEY_CHECKS=0;
-- UltiCode Migration: V13__solution_enrich_content
-- Enrich solution seed data with full code implementations, explanations, and complexity analysis.

-- sol-001: Two Sum — TypeScript HashMap
UPDATE `solutions` SET `content` = '# 哈希表解法 — O(n) 时间复杂度\n\n## 思路\n\n遍历数组，将每个元素的值和索引存入哈希表。对于当前元素 `nums[i]`，检查 `target - nums[i]` 是否已在哈希表中。如果存在，说明找到了一对解。\n\n关键点：边查边插，不需要先将所有元素存入哈希表。\n\n```typescript\nfunction twoSum(nums: number[], target: number): number[] {\n  const map = new Map<number, number>();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) {\n      return [map.get(complement)!, i];\n    }\n    map.set(nums[i], i);\n  }\n  return [];\n}\n```\n\n## 复杂度分析\n\n- **时间复杂度**：O(n)，只需一次遍历，哈希表查找 O(1)\n- **空间复杂度**：O(n)，最坏情况需要存储 n-1 个元素', `summary` = 'O(n) 时间复杂度的哈希表解法，遍历数组时边查边插，一次遍历即可找到目标对。' WHERE `id` = 'sol-001';

-- sol-002: Two Sum — Brute Force JavaScript
UPDATE `solutions` SET `content` = '# 暴力枚举解法\n\n## 思路\n\n最直观的方法：双重循环枚举所有可能的数对 `(i, j)`，检查 `nums[i] + nums[j] === target`。\n\n虽然时间复杂度不理想，但实现简单，适合理解问题本质。\n\n```javascript\nfunction twoSum(nums, target) {\n  for (let i = 0; i < nums.length; i++) {\n    for (let j = i + 1; j < nums.length; j++) {\n      if (nums[i] + nums[j] === target) {\n        return [i, j];\n      }\n    }\n  }\n  return [];\n}\n```\n\n## 复杂度分析\n\n- **时间复杂度**：O(n²)，两层嵌套循环\n- **空间复杂度**：O(1)，不需要额外空间', `summary` = 'O(n²) 暴力枚举解法，双重循环检查所有数对。实现简单，适合入门理解。' WHERE `id` = 'sol-002';

-- sol-003: Two Sum — TypeScript Map
UPDATE `solutions` SET `content` = '# TypeScript Map 解法\n\n## 思路\n\n使用 TypeScript 的 `Map` 对象，利用其 `has()` 和 `get()` 方法实现 O(1) 查找。与普通对象 `{}` 不同，`Map` 的 key 可以是任意类型，且不会受到原型链属性的干扰。\n\n```typescript\nfunction twoSum(nums: number[], target: number): number[] {\n  const prev = new Map<number, number>();\n\n  for (let i = 0; i < nums.length; i++) {\n    const need = target - nums[i];\n    if (prev.has(need)) {\n      return [prev.get(need)!, i];\n    }\n    prev.set(nums[i], i);\n  }\n\n  throw new Error("No solution found");\n}\n```\n\n## 为什么用 Map 而不是 {}\n\n1. `Map.has()` 不会误判原型链上的属性（如 `"constructor"`）\n2. key 可以是 `number` 类型，不需要字符串转换\n3. `Map.get()` 返回 `undefined` 而非实际值时语义清晰\n\n## 复杂度分析\n\n- **时间复杂度**：O(n)\n- **空间复杂度**：O(n)', `summary` = 'TypeScript Map 解法，利用 Map 的类型安全和 O(1) 查找特性，比普通对象更可靠。' WHERE `id` = 'sol-003';

-- sol-004: Two Sum — JavaScript HashMap
UPDATE `solutions` SET `content` = '# JavaScript 哈希表解法\n\n## 思路\n\n使用原生 `Map` 对象实现 O(n) 解法。与普通对象相比，`Map` 在 JavaScript 中性能更优，且支持任意类型的 key。\n\n```javascript\nfunction twoSum(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) {\n      return [map.get(complement), i];\n    }\n    map.set(nums[i], i);\n  }\n}\n```\n\n## 关键细节\n\n- **边查边插**：先检查 complement 是否存在，再插入当前元素。这保证不会用同一个元素匹配自己\n- **返回值**：题目保证有且仅有一个解，所以不需要处理无解情况\n- **Map vs Object**：JavaScript 中 Map 的 `has/get/set` 操作比对象属性访问更快\n\n## 复杂度分析\n\n- **时间复杂度**：O(n)，一次遍历\n- **空间复杂度**：O(n)，哈希表存储', `summary` = 'JavaScript Map 实现 O(n) 两数之和，边查边插避免自匹配，利用原生 Map 的高性能查找。' WHERE `id` = 'sol-004';

-- sol-005: Longest Substring — Sliding Window
UPDATE `solutions` SET `content` = '# 滑动窗口解法\n\n## 思路\n\n维护一个滑动窗口 `[left, right]`，使用 `Set` 记录窗口内的字符。当遇到重复字符时，收缩左边界直到重复字符移出窗口。\n\n核心操作：右指针扩展窗口，左指针收缩窗口消除重复。\n\n```typescript\nfunction lengthOfLongestSubstring(s: string): number {\n  const set = new Set<string>();\n  let left = 0;\n  let maxLen = 0;\n\n  for (let right = 0; right < s.length; right++) {\n    while (set.has(s[right])) {\n      set.delete(s[left]);\n      left++;\n    }\n    set.add(s[right]);\n    maxLen = Math.max(maxLen, right - left + 1);\n  }\n\n  return maxLen;\n}\n```\n\n## 优化：直接跳到重复位置\n\n可以用 `Map` 记录每个字符最后出现的位置，遇到重复时直接将 `left` 跳到 `lastSeen[char] + 1`，省去逐个删除。\n\n```typescript\nfunction lengthOfLongestSubstring(s: string): number {\n  const lastSeen = new Map<string, number>();\n  let left = 0;\n  let maxLen = 0;\n\n  for (let right = 0; right < s.length; right++) {\n    if (lastSeen.has(s[right]) && lastSeen.get(s[right])! >= left) {\n      left = lastSeen.get(s[right])! + 1;\n    }\n    lastSeen.set(s[right], right);\n    maxLen = Math.max(maxLen, right - left + 1);\n  }\n\n  return maxLen;\n}\n```\n\n## 复杂度分析\n\n- **时间复杂度**：O(n)，每个字符最多被访问两次（扩展+收缩）\n- **空间复杂度**：O(min(m, n))，其中 m 是字符集大小', `summary` = 'O(n) 滑动窗口解法，左指针收缩消除重复字符。优化版用 Map 跳转替代逐个删除。' WHERE `id` = 'sol-005';

-- sol-006: Merge Intervals — Sort and Sweep
UPDATE `solutions` SET `content` = '# 排序扫描合并\n\n## 思路\n\n1. 按区间起点排序\n2. 遍历排序后的区间，维护当前合并区间 `[start, end]`\n3. 如果下一个区间的起点 <= end，则合并（更新 end）\n4. 否则将当前区间加入结果，开始新的合并区间\n\n```javascript\nfunction merge(intervals) {\n  intervals.sort((a, b) => a[0] - b[0]);\n  const result = [];\n  let [start, end] = intervals[0];\n\n  for (let i = 1; i < intervals.length; i++) {\n    const [currStart, currEnd] = intervals[i];\n    if (currStart <= end) {\n      // Overlap — merge\n      end = Math.max(end, currEnd);\n    } else {\n      // No overlap — push and reset\n      result.push([start, end]);\n      start = currStart;\n      end = currEnd;\n    }\n  }\n  result.push([start, end]);\n\n  return result;\n}\n```\n\n## 边界情况\n\n- 空输入：直接返回 `[]`\n- 单个区间：直接返回\n- 完全包含：`[1,5]` 和 `[2,3]` 合并为 `[1,5]`\n- 相邻区间：`[1,2]` 和 `[2,3]` 合并为 `[1,3]`\n\n## 复杂度分析\n\n- **时间复杂度**：O(n log n)，排序占主导\n- **空间复杂度**：O(n)，结果数组', `summary` = 'O(n log n) 排序后扫描合并，遍历时维护当前合并区间，遇到不重叠则输出。' WHERE `id` = 'sol-006';

-- sol-007: Median of Two Sorted Arrays — Binary Search
UPDATE `solutions` SET `content` = '# 二分查找 Partition\n\n## 思路\n\n在较短的数组上进行二分搜索，将两个数组分成左右两部分，使得左半部分的最大值 <= 右半部分的最小值。\n\n设 `A` 为较短数组，在 `A` 上做 partition。对于 partition 位置 `i`，`B` 的对应位置 `j = (m + n + 1) / 2 - i`。\n\n```typescript\nfunction findMedianSortedArrays(nums1: number[], nums2: number[]): number {\n  if (nums1.length > nums2.length) {\n    return findMedianSortedArrays(nums2, nums1);\n  }\n\n  const m = nums1.length;\n  const n = nums2.length;\n  let lo = 0;\n  let hi = m;\n\n  while (lo <= hi) {\n    const i = Math.floor((lo + hi) / 2);\n    const j = Math.floor((m + n + 1) / 2) - i;\n\n    const maxLeftA = i === 0 ? -Infinity : nums1[i - 1];\n    const minRightA = i === m ? Infinity : nums1[i];\n    const maxLeftB = j === 0 ? -Infinity : nums2[j - 1];\n    const minRightB = j === n ? Infinity : nums2[j];\n\n    if (maxLeftA <= minRightB && maxLeftB <= minRightA) {\n      if ((m + n) % 2 === 1) {\n        return Math.max(maxLeftA, maxLeftB);\n      }\n      return (Math.max(maxLeftA, maxLeftB) + Math.min(minRightA, minRightB)) / 2;\n    } else if (maxLeftA > minRightB) {\n      hi = i - 1;\n    } else {\n      lo = i + 1;\n    }\n  }\n\n  throw new Error("Input arrays are not sorted");\n}\n```\n\n## 关键点\n\n- **在短数组上二分**：保证 j 不会越界\n- **虚拟边界**：i=0 和 i=m 时用 ±Infinity 处理\n- **奇偶统一**：`(m+n+1)/2` 向上取整，左半部分多一个元素\n\n## 复杂度分析\n\n- **时间复杂度**：O(log(min(m, n)))\n- **空间复杂度**：O(1)', `summary` = 'O(log(min(m,n))) 二分查找，在较短数组上 partition，保证左半最大 <= 右半最小。' WHERE `id` = 'sol-007';

-- sol-008: Number of Islands — Iterative DFS
UPDATE `solutions` SET `content` = '# 迭代 DFS 洪水填充\n\n## 思路\n\n使用显式栈替代递归，避免递归栈溢出。遍历网格，遇到陆地 ''1'' 时用 DFS 将整个岛屿标记为已访问（改为 ''0''）。\n\n```typescript\nfunction numIslands(grid: string[][]): number {\n  if (grid.length === 0) return 0;\n\n  const rows = grid.length;\n  const cols = grid[0].length;\n  let count = 0;\n\n  for (let r = 0; r < rows; r++) {\n    for (let c = 0; c < cols; c++) {\n      if (grid[r][c] !== "1") continue;\n\n      count++;\n      const stack: [number, number][] = [[r, c]];\n\n      while (stack.length > 0) {\n        const [cr, cc] = stack.pop()!;\n        if (cr < 0 || cr >= rows || cc < 0 || cc >= cols) continue;\n        if (grid[cr][cc] !== "1") continue;\n\n        grid[cr][cc] = "0"; // Mark visited\n        stack.push([cr + 1, cc]);\n        stack.push([cr - 1, cc]);\n        stack.push([cr, cc + 1]);\n        stack.push([cr, cc - 1]);\n      }\n    }\n  }\n\n  return count;\n}\n```\n\n## 为什么用迭代而非递归\n\n1. **避免栈溢出**：最坏情况 200x200 网格全部是陆地，递归深度 40000\n2. **性能更可控**：显式栈的内存使用可预测\n3. **可中断恢复**：迭代版本可以改造为支持暂停/恢复\n\n## 复杂度分析\n\n- **时间复杂度**：O(m × n)，每个格子最多访问一次\n- **空间复杂度**：O(min(m, n))，栈的最大深度取决于网格短边', `summary` = '基于栈的 O(mn) 迭代 DFS，显式栈避免递归溢出，遍历标记整个岛屿。' WHERE `id` = 'sol-008';

SET FOREIGN_KEY_CHECKS=1;
