SET FOREIGN_KEY_CHECKS=0;

-- ============================================================================
-- V16: Seed problems for recommendation system (IDs 9-40, 32 problems)
-- ============================================================================

-- Table: problems (32 rows)
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (9,'maximum-subarray','最大子数组和','Medium',44.80,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (10,'product-of-array-except-self','除自身以外数组的乘积','Medium',64.50,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (11,'container-with-most-water','盛最多水的容器','Medium',54.30,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (12,'trapping-rain-water','接雨水','Hard',58.70,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (13,'valid-palindrome','验证回文串','Easy',46.50,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (14,'group-anagrams','字母异位词分组','Medium',66.70,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (15,'minimum-window-substring','最小覆盖子串','Hard',41.50,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (16,'longest-palindromic-substring','最长回文子串','Medium',36.80,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (17,'top-k-frequent-elements','前 K 个高频元素','Medium',63.60,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (18,'find-all-anagrams-in-a-string','找到字符串中所有字母异位词','Medium',52.40,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (19,'subarray-sum-equals-k','和为 K 的子数组','Medium',45.20,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (20,'climbing-stairs','爬楼梯','Easy',52.80,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (21,'coin-change','零钱兑换','Medium',41.50,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (22,'longest-increasing-subsequence','最长递增子序列','Medium',52.80,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (23,'edit-distance','编辑距离','Hard',56.30,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (24,'binary-tree-inorder-traversal','二叉树的中序遍历','Easy',76.20,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (25,'binary-tree-level-order-traversal','二叉树的层序遍历','Medium',64.80,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (26,'binary-tree-maximum-path-sum','二叉树中的最大路径和','Hard',38.20,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (27,'clone-graph','克隆图','Medium',59.30,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (28,'course-schedule','课程表','Medium',53.70,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (29,'word-ladder','单词接龙','Hard',47.60,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (30,'binary-search','二分查找','Easy',55.20,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (31,'search-in-rotated-sorted-array','搜索旋转排序数组','Medium',42.80,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (32,'find-minimum-in-rotated-sorted-array','寻找旋转排序数组中的最小值','Medium',57.30,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (33,'valid-parentheses','有效的括号','Easy',43.50,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (34,'daily-temperatures','每日温度','Medium',66.30,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (35,'min-stack','最小栈','Medium',56.20,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (36,'jump-game','跳跃游戏','Medium',43.50,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (37,'task-scheduler','任务调度器','Medium',58.50,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (38,'candy','分发糖果','Hard',48.60,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (39,'powx-n','Pow(x, n)','Medium',37.20,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);
INSERT INTO `problems` (`id`, `slug`, `title`, `difficulty`, `acceptance_rate`, `status`, `is_premium`, `has_solution`, `completed_time`, `is_published`, `published_at`, `published_by`, `is_deleted`, `deleted_at`, `deleted_by`, `flag_notes`, `flag_reason`, `flag_reported_at`, `flag_reported_by`, `flag_reviewed_at`, `flag_reviewed_by`, `flag_status`, `is_flagged`, `created_at`, `updated_at`, `version`) VALUES (40,'reverse-linked-list','反转链表','Easy',74.50,'todo',0,1,NULL,1,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NOW(3),NOW(3),1);

-- Table: problem_details (32 rows)
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-maximum-subarray',9,'maximum-subarray','给定一个整数数组 nums，找到一个具有最大和的连续子数组（子数组最少包含一个元素），返回其最大和。','[{\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',12400,620,1530.0,NOW(3),'如果要求返回最大子数组本身而不仅仅是和呢？','[\"$1 \\\\leq nums.length \\\\leq 10^5$\", \"$-10^4 \\\\leq nums[i] \\\\leq 10^4$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-product-of-array-except-self',10,'product-of-array-except-self','给定一个整数数组 nums，返回数组 answer，其中 answer[i] 等于 nums 中除 nums[i] 之外其余各元素的乘积。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"meta\", \"name\": \"Meta\"}, {\"id\": \"apple\", \"name\": \"Apple\"}]',14200,710,1480.0,NOW(3),'能在 O(1) 的额外空间复杂度内完成吗？（输出数组不算额外空间）','[\"$2 \\\\leq nums.length \\\\leq 10^5$\", \"$-30 \\\\leq nums[i] \\\\leq 30$\", \"保证数组中任意元素的全部前缀元素和后缀元素乘积都在 32 位整数范围内。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-container-with-most-water',11,'container-with-most-water','给定一个长度为 n 的整数数组 height，有 n 条垂线，第 i 条线的两个端点是 (i, 0) 和 (i, height[i])。找出其中的两条线，使得它们与 x 轴共同构成的容器可以容纳最多的水。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"bloomberg\", \"name\": \"Bloomberg\"}]',15800,790,1550.0,NOW(3),'如何证明双指针方法的正确性？','[\"$n == height.length$\", \"$2 \\\\leq n \\\\leq 10^5$\", \"$0 \\\\leq height[i] \\\\leq 10^4$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-trapping-rain-water',12,'trapping-rain-water','给定 n 个非负整数表示每个宽度为 1 的柱子的高度图，计算按此排列的柱子下雨之后能接多少雨水。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"meta\", \"name\": \"Meta\"}]',18200,910,1900.0,NOW(3),'能只用 O(1) 的额外空间解决吗？','[\"$n == height.length$\", \"$1 \\\\leq n \\\\leq 2 \\\\times 10^4$\", \"$0 \\\\leq height[i] \\\\leq 10^5$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-valid-palindrome',13,'valid-palindrome','给定一个字符串 s，验证它是否是回文串。只考虑字母和数字字符，忽略大小写。','[{\"id\": \"meta\", \"name\": \"Meta\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',3200,160,1100.0,NOW(3),NULL,'[\"$1 \\\\leq s.length \\\\leq 2 \\\\times 10^5$\", \"s 由 ASCII 字符组成。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-group-anagrams',14,'group-anagrams','给定一个字符串数组，将字母异位词组合在一起。字母异位词是由相同字母重新排列形成的不同字符串。','[{\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"uber\", \"name\": \"Uber\"}]',9800,490,1460.0,NOW(3),'你能用 O(nk) 的时间复杂度解决吗？','[\"$1 \\\\leq strs.length \\\\leq 10^4$\", \"$0 \\\\leq strs[i].length \\\\leq 100$\", \"strs[i] 仅包含小写英文字母。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-minimum-window-substring',15,'minimum-window-substring','给定字符串 s 和 t，返回 s 中涵盖 t 所有字符（包括重复字符）的最小子串。如果不存在这样的子串，返回空字符串。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"meta\", \"name\": \"Meta\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',14500,725,1880.0,NOW(3),'如果要求返回所有满足条件的最小窗口呢？','[\"$1 \\\\leq s.length, t.length \\\\leq 10^5$\", \"s 和 t 由英文字母组成。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-longest-palindromic-substring',16,'longest-palindromic-substring','给定一个字符串 s，找到 s 中最长的回文子串。','[{\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',13200,660,1520.0,NOW(3),'能找到 O(n) 时间复杂度的解法吗？（Manacher 算法）','[\"$1 \\\\leq s.length \\\\leq 1000$\", \"s 仅由英文字母和数字组成。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-top-k-frequent-elements',17,'top-k-frequent-elements','给定一个整数数组 nums 和一个整数 k，返回数组中出现频率前 k 高的元素。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"meta\", \"name\": \"Meta\"}]',11500,575,1490.0,NOW(3),'你能用低于 O(n log n) 的时间复杂度解决吗？','[\"$1 \\\\leq nums.length \\\\leq 10^5$\", \"$-10^4 \\\\leq nums[i] \\\\leq 10^4$\", \"$1 \\\\leq k \\\\leq 数组中不同元素的个数$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-find-all-anagrams-in-a-string',18,'find-all-anagrams-in-a-string','给定两个字符串 s 和 p，找到 s 中所有 p 的字母异位词的子串起始索引。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',7500,375,1510.0,NOW(3),NULL,'[\"$1 \\\\leq s.length, p.length \\\\leq 3 \\\\times 10^4$\", \"s 和 p 仅包含小写英文字母。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-subarray-sum-equals-k',19,'subarray-sum-equals-k','给定一个整数数组 nums 和一个整数 k，统计并返回数组中和为 k 的连续子数组的个数。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"meta\", \"name\": \"Meta\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',10500,525,1540.0,NOW(3),'如果数组中存在负数呢？前缀和方法是否仍然适用？','[\"$1 \\\\leq nums.length \\\\leq 2 \\\\times 10^4$\", \"$-1000 \\\\leq nums[i] \\\\leq 1000$\", \"$-10^7 \\\\leq k \\\\leq 10^7$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-climbing-stairs',20,'climbing-stairs','给定 n 阶楼梯，每次可以爬 1 或 2 个台阶，有多少种不同的方法可以爬到楼顶。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',4800,240,1060.0,NOW(3),'如果每次可以爬 1 到 m 个台阶呢？','[\"$1 \\\\leq n \\\\leq 45$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-coin-change',21,'coin-change','给定不同面额的硬币 coins 和一个总金额 amount，计算凑成总金额所需的最少硬币数。','[{\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',12800,640,1560.0,NOW(3),'如果需要输出具体的硬币组合而不仅仅是最少数量呢？','[\"$1 \\\\leq coins.length \\\\leq 12$\", \"$1 \\\\leq coins[i] \\\\leq 2^{31} - 1$\", \"$0 \\\\leq amount \\\\leq 10^4$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-longest-increasing-subsequence',22,'longest-increasing-subsequence','给定一个整数数组 nums，找到最长严格递增子序列的长度。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',9200,460,1570.0,NOW(3),'你能用 O(n log n) 的时间复杂度解决吗？','[\"$1 \\\\leq nums.length \\\\leq 2500$\", \"$-10^4 \\\\leq nums[i] \\\\leq 10^4$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-edit-distance',23,'edit-distance','给定两个单词 word1 和 word2，返回将 word1 转换成 word2 所使用的最少操作数（插入、删除、替换）。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"meta\", \"name\": \"Meta\"}, {\"id\": \"bloomberg\", \"name\": \"Bloomberg\"}]',8800,440,1920.0,NOW(3),'如果只允许插入和删除操作呢？','[\"$0 \\\\leq word1.length, word2.length \\\\leq 500$\", \"word1 和 word2 由小写英文字母组成。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-binary-tree-inorder-traversal',24,'binary-tree-inorder-traversal','给定一个二叉树的根节点 root，返回它的中序遍历结果。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',2500,125,1080.0,NOW(3),'你能用迭代方式实现吗？','[\"树中节点数目在范围 $[1, 100]$ 内\", \"$-100 \\\\leq Node.val \\\\leq 100$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-binary-tree-level-order-traversal',25,'binary-tree-level-order-traversal','给定一个二叉树的根节点 root，返回其节点值的层序遍历（即逐层地，从左到右访问所有节点）。','[{\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',7200,360,1450.0,NOW(3),'能实现自底向上的层序遍历吗？','[\"树中节点数目在范围 $[0, 2000]$ 内\", \"$-1000 \\\\leq Node.val \\\\leq 1000$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-binary-tree-maximum-path-sum',26,'binary-tree-maximum-path-sum','给定一个二叉树的根节点 root，返回其最大路径和。路径被定义为一条节点序列，序列中每对相邻节点之间都有一条边相连。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"meta\", \"name\": \"Meta\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',8200,410,1850.0,NOW(3),NULL,'[\"树中节点数目范围在 $[1, 3 \\\\times 10^4]$ 内\", \"$-1000 \\\\leq Node.val \\\\leq 1000$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-clone-graph',27,'clone-graph','给定无向连通图中一个节点的引用，返回该图的深拷贝（克隆）。图中的每个节点都包含它的值和邻接列表。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"meta\", \"name\": \"Meta\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',5800,290,1470.0,NOW(3),NULL,'[\"节点数在 $[0, 100]$ 范围内\", \"$1 \\\\leq Node.val \\\\leq 100$\", \"Node.val 对于每个节点是唯一的。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-course-schedule',28,'course-schedule','给定 numCourses 门课程以及 prerequisites 数组，判断是否可能完成所有课程的学习。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',8600,430,1500.0,NOW(3),'如果需要返回一种可行的修课顺序呢？','[\"$1 \\\\leq numCourses \\\\leq 2000$\", \"$0 \\\\leq prerequisites.length \\\\leq 5000$\", \"prerequisites[i].length == 2\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-word-ladder',29,'word-ladder','给定两个单词 beginWord 和 endWord 以及一个字典 wordList，找到从 beginWord 到 endWord 的最短转换序列的长度。每次转换只能改变一个字母。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"meta\", \"name\": \"Meta\"}]',6800,340,1930.0,NOW(3),'如果使用双向 BFS 能否进一步优化？','[\"$1 \\\\leq beginWord.length \\\\leq 10$\", \"$1 \\\\leq wordList.length \\\\leq 5000$\", \"beginWord、endWord 和 wordList[i] 由小写英文字母组成。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-binary-search',30,'binary-search','给定一个已排序的整数数组 nums 和一个目标值 target，在数组中找到目标值并返回其索引。如果目标值不存在，返回 -1。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',1800,90,1070.0,NOW(3),NULL,'[\"$1 \\\\leq nums.length \\\\leq 10^4$\", \"$-10^4 \\\\leq nums[i], target \\\\leq 10^4$\", \"nums 中的所有元素互不相同且按升序排列。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-search-in-rotated-sorted-array',31,'search-in-rotated-sorted-array','给定一个在未知 pivot 点旋转后的排序数组 nums 和一个目标值 target，返回 target 在数组中的索引。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"meta\", \"name\": \"Meta\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',13500,675,1580.0,NOW(3),'如果数组中有重复元素呢？','[\"$1 \\\\leq nums.length \\\\leq 5000$\", \"$-10^4 \\\\leq nums[i] \\\\leq 10^4$\", \"nums 中的每个值都独一无二。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-find-minimum-in-rotated-sorted-array',32,'find-minimum-in-rotated-sorted-array','给定一个在某个 pivot 点旋转过的排序数组 nums，返回数组中的最小元素。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',6800,340,1460.0,NOW(3),'能在 O(log n) 时间内解决吗？','[\"$1 \\\\leq nums.length \\\\leq 5000$\", \"$-5000 \\\\leq nums[i] \\\\leq 5000$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-valid-parentheses',33,'valid-parentheses','给定一个只包括括号字符的字符串 s，判断字符串是否有效。有效字符串需满足括号必须以正确的顺序闭合。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"meta\", \"name\": \"Meta\"}]',4800,240,1090.0,NOW(3),NULL,'[\"$1 \\\\leq s.length \\\\leq 10^4$\", \"s 仅由括号字符组成。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-daily-temperatures',34,'daily-temperatures','给定一个整数数组 temperatures，表示每天的温度，返回一个数组 answer，其中 answer[i] 是指对于第 i 天，下一个更高温度出现在几天后。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',7800,390,1510.0,NOW(3),NULL,'[\"$1 \\\\leq temperatures.length \\\\leq 10^5$\", \"$30 \\\\leq temperatures[i] \\\\leq 100$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-min-stack',35,'min-stack','设计一个支持 push、pop、top 操作，并能在常数时间内检索到最小元素的栈。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"bloomberg\", \"name\": \"Bloomberg\"}]',6500,325,1480.0,NOW(3),NULL,'[\"$-2^{31} \\\\leq val \\\\leq 2^{31} - 1$\", \"pop、top 和 getMin 操作总是在非空栈上调用。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-jump-game',36,'jump-game','给定一个非负整数数组 nums，你最初位于数组的第一个下标，每个元素代表在该位置可以跳跃的最大步数。判断是否能到达最后一个下标。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',9500,475,1470.0,NOW(3),'如果要求到达末尾的最少跳跃次数呢？','[\"$1 \\\\leq nums.length \\\\leq 10^4$\", \"$0 \\\\leq nums[i] \\\\leq 10^5$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-task-scheduler',37,'task-scheduler','给定一个用字符数组表示的 CPU 任务列表 tasks 和一个冷却时间 n，计算完成所有任务需要的最短时间。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"meta\", \"name\": \"Meta\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',7200,360,1560.0,NOW(3),NULL,'[\"$1 \\\\leq tasks.length \\\\leq 10^4$\", \"$0 \\\\leq n \\\\leq 100$\", \"tasks[i] 是大写英文字母。\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-candy',38,'candy','给定 n 个孩子站成一排，每个孩子有一个评分。你需要按照规则给这些孩子分发糖果：每个孩子至少一颗，评分更高的孩子比相邻孩子获得更多糖果。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}]',5600,280,1810.0,NOW(3),NULL,'[\"$n == ratings.length$\", \"$1 \\\\leq n \\\\leq 2 \\\\times 10^4$\", \"$0 \\\\leq ratings[i] \\\\leq 2 \\\\times 10^4$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-powx-n',39,'powx-n','实现 pow(x, n)，即计算 x 的整数 n 次幂函数。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"meta\", \"name\": \"Meta\"}]',4200,210,1430.0,NOW(3),'你能用迭代方式实现快速幂吗？','[\"$-100.0 \\\\leq x \\\\leq 100.0$\", \"$-2^{31} \\\\leq n \\\\leq 2^{31} - 1$\", \"$-10^4 \\\\leq x^n \\\\leq 10^4$\"]',NULL,NULL);
INSERT INTO `problem_details` (`id`, `problem_id`, `slug`, `summary`, `companies`, `likes`, `dislikes`, `difficulty_rating`, `updated_at`, `follow_up`, `constraints_json`, `hints`, `interactions`) VALUES ('pd-reverse-linked-list',40,'reverse-linked-list','给定单链表的头节点 head，反转链表并返回反转后的链表。','[{\"id\": \"google\", \"name\": \"Google\"}, {\"id\": \"amazon\", \"name\": \"Amazon\"}, {\"id\": \"microsoft\", \"name\": \"Microsoft\"}]',3800,190,1060.0,NOW(3),'你能用递归和迭代两种方式实现吗？','[\"链表中节点的数目范围在 $[0, 5000]$ 内\", \"$-5000 \\\\leq Node.val \\\\leq 5000$\"]',NULL,NULL);

-- ============================================================================
-- Update usage_count for existing tags
-- ============================================================================
-- V2 initial counts + new usages from problems 9-40:
-- algorithms: 5 + 0 (not tagging new problems with algorithms to keep focused) = 5
-- array: 3 + 10 (9,10,11,12,17,19,30,31,32,36,37,38) = 13 -> +10
-- backtracking: 0 + 0 = 0
-- bfs: 1 + 4 (21,25,27,28,29) = 5 -> +4
-- binary-search: 1 + 5 (22,30,31,32,39) = 6 -> +5
-- bit-manipulation: 0 + 0 = 0
-- concurrency: 1 + 0 = 1
-- database: 1 + 0 = 1
-- design: 0 + 1 (35) = 1 -> +1
-- dfs: 1 + 4 (26,27,28,29) = 5 -> +4
-- divide-and-conquer: 1 + 0 = 1
-- dynamic-programming: 0 + 7 (9,16,20,21,22,23,26,36) = 8 -> +8
-- graph: 0 + 3 (27,28,29) = 3 -> +3
-- greedy: 0 + 4 (11,36,37,38) = 4 -> +4
-- hash-table: 2 + 5 (14,15,17,18,19,29) = 7 -> +5
-- heap: 0 + 2 (17,37) = 2 -> +2
-- intervals: 1 + 0 = 1
-- linked-list: 0 + 1 (40) = 1 -> +1
-- math: 0 + 1 (20,39) = 2 -> +2
-- matrix: 1 + 0 = 1
-- queue: 0 + 0 = 0
-- recursion: 0 + 3 (24,39,40) = 3 -> +3
-- shell: 1 + 0 = 1
-- sliding-window: 1 + 2 (15,18) = 3 -> +2
-- sorting: 1 + 1 (14) = 2 -> +1
-- stack: 0 + 4 (12,24,33,34,35) = 5 -> +5
-- string: 1 + 7 (13,14,15,16,18,23,29,33) = 8 -> +7
-- tree: 0 + 3 (24,25,26) = 3 -> +3
-- two-pointers: 0 + 4 (11,12,13,29) = 4 -> +4
-- union-find: 1 + 0 = 1

UPDATE `problem_tags` SET `usage_count` = 13, `updated_at` = NOW(3) WHERE `id` = 'array';
UPDATE `problem_tags` SET `usage_count` = 5, `updated_at` = NOW(3) WHERE `id` = 'bfs';
UPDATE `problem_tags` SET `usage_count` = 6, `updated_at` = NOW(3) WHERE `id` = 'binary-search';
UPDATE `problem_tags` SET `usage_count` = 1, `updated_at` = NOW(3) WHERE `id` = 'design';
UPDATE `problem_tags` SET `usage_count` = 5, `updated_at` = NOW(3) WHERE `id` = 'dfs';
UPDATE `problem_tags` SET `usage_count` = 8, `updated_at` = NOW(3) WHERE `id` = 'dynamic-programming';
UPDATE `problem_tags` SET `usage_count` = 3, `updated_at` = NOW(3) WHERE `id` = 'graph';
UPDATE `problem_tags` SET `usage_count` = 4, `updated_at` = NOW(3) WHERE `id` = 'greedy';
UPDATE `problem_tags` SET `usage_count` = 7, `updated_at` = NOW(3) WHERE `id` = 'hash-table';
UPDATE `problem_tags` SET `usage_count` = 2, `updated_at` = NOW(3) WHERE `id` = 'heap';
UPDATE `problem_tags` SET `usage_count` = 1, `updated_at` = NOW(3) WHERE `id` = 'linked-list';
UPDATE `problem_tags` SET `usage_count` = 2, `updated_at` = NOW(3) WHERE `id` = 'math';
UPDATE `problem_tags` SET `usage_count` = 3, `updated_at` = NOW(3) WHERE `id` = 'recursion';
UPDATE `problem_tags` SET `usage_count` = 3, `updated_at` = NOW(3) WHERE `id` = 'sliding-window';
UPDATE `problem_tags` SET `usage_count` = 2, `updated_at` = NOW(3) WHERE `id` = 'sorting';
UPDATE `problem_tags` SET `usage_count` = 5, `updated_at` = NOW(3) WHERE `id` = 'stack';
UPDATE `problem_tags` SET `usage_count` = 8, `updated_at` = NOW(3) WHERE `id` = 'string';
UPDATE `problem_tags` SET `usage_count` = 3, `updated_at` = NOW(3) WHERE `id` = 'tree';
UPDATE `problem_tags` SET `usage_count` = 4, `updated_at` = NOW(3) WHERE `id` = 'two-pointers';

-- ============================================================================
-- Table: problem_tag_relations (new relations for problems 9-40)
-- ============================================================================
-- Array problems (9-12)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (9,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (9,'dynamic-programming');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (10,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (11,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (11,'two-pointers');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (11,'greedy');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (12,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (12,'two-pointers');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (12,'stack');
-- String problems (13-16)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (13,'string');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (13,'two-pointers');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (14,'string');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (14,'hash-table');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (14,'sorting');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (15,'string');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (15,'sliding-window');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (15,'hash-table');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (16,'string');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (16,'dynamic-programming');
-- Hash Table problems (17-19)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (17,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (17,'hash-table');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (17,'heap');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (17,'sorting');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (18,'string');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (18,'hash-table');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (18,'sliding-window');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (19,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (19,'hash-table');
-- Dynamic Programming problems (20-23)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (20,'dynamic-programming');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (20,'math');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (21,'dynamic-programming');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (21,'bfs');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (22,'dynamic-programming');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (22,'binary-search');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (23,'dynamic-programming');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (23,'string');
-- Tree problems (24-26)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (24,'tree');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (24,'stack');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (24,'recursion');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (25,'tree');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (25,'bfs');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (26,'tree');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (26,'dynamic-programming');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (26,'dfs');
-- Graph problems (27-29)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (27,'graph');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (27,'dfs');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (27,'bfs');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (28,'graph');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (28,'dfs');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (28,'bfs');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (29,'graph');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (29,'bfs');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (29,'string');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (29,'hash-table');
-- Binary Search problems (30-32)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (30,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (30,'binary-search');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (31,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (31,'binary-search');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (32,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (32,'binary-search');
-- Stack/Queue problems (33-35)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (33,'string');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (33,'stack');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (34,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (34,'stack');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (35,'stack');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (35,'design');
-- Greedy problems (36-38)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (36,'greedy');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (36,'dynamic-programming');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (36,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (37,'greedy');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (37,'heap');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (37,'array');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (38,'greedy');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (38,'array');
-- Math problem (39)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (39,'math');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (39,'recursion');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (39,'binary-search');
-- Linked List problem (40)
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (40,'linked-list');
INSERT INTO `problem_tag_relations` (`problem_id`, `tag_id`) VALUES (40,'recursion');

SET FOREIGN_KEY_CHECKS=1;
