SET FOREIGN_KEY_CHECKS=0;
-- UltiCode Migration: V17__recommendation_seed_submissions
-- Seed submission data for recommendation engine testing
-- ~400 submissions across 19 users and 40 problems

-- ============================================================================
-- BEGINNER USERS (5 users, ~5 submissions each, mainly Easy, ~30% pass)
-- user-emma, user-yuki, user-sara, user-lily, user-max
-- ============================================================================

-- user-emma: mostly Easy with some WA
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-emma','typescript','// two-sum solution',  'Accepted',65,42.3,NULL,'2026-01-20 14:10:00',78.5,65.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),6,'user-emma','typescript','// combine tables',        'Accepted',35,38.1,NULL,'2026-01-21 09:30:00',82.3,55.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-emma','javascript','// brute force attempt',    'Wrong Answer',0,0,NULL,'2026-01-22 16:45:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-emma','typescript','// valid palindrome',       'Accepted',48,40.5,NULL,'2026-01-23 11:20:00',75.2,68.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-emma','javascript','// wrong case handling',    'Wrong Answer',0,0,NULL,'2026-01-23 11:25:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-emma','typescript','// climbing stairs dp',     'Accepted',32,38.7,NULL,'2026-01-25 08:00:00',88.1,72.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-emma','typescript','// inorder traversal',     'Accepted',42,41.2,NULL,'2026-02-01 10:15:00',70.6,58.4);

-- user-yuki: Easy problems, some Medium attempts
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-yuki','typescript','// two-sum hash map',      'Accepted',55,43.1,NULL,'2025-12-15 10:00:00',82.1,71.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),6,'user-yuki','typescript','// combine tables sql',      'Accepted',28,36.4,NULL,'2025-12-16 14:30:00',90.5,78.9);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-yuki','javascript','// palindrome attempt',       'Accepted',52,39.8,NULL,'2025-12-18 09:00:00',76.8,62.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-yuki','typescript','// binary search',          'Accepted',40,38.2,NULL,'2025-12-20 11:30:00',85.3,70.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-yuki','typescript','// valid parentheses',       'Accepted',38,37.5,NULL,'2025-12-22 08:45:00',80.2,66.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),2,'user-yuki','typescript','// sliding window attempt',   'Wrong Answer',0,0,NULL,'2025-12-25 16:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-yuki','typescript','// reverse linked list',       'Accepted',35,39.1,NULL,'2026-01-05 13:00:00',72.1,55.3);

-- user-sara: Easy + some Medium
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-sara','javascript','// two-sum',               'Accepted',60,41.5,NULL,'2025-12-10 09:00:00',75.3,63.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-sara','typescript','// valid palindrome',       'Accepted',45,38.9,NULL,'2025-12-12 11:00:00',80.5,68.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-sara','python','// fibonacci dp',           'Accepted',28,35.2,NULL,'2025-12-15 15:30:00',85.2,74.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-sara','typescript','// anagrams sort',         'Wrong Answer',0,0,NULL,'2025-12-18 10:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-sara','typescript','// anagrams hash map',      'Accepted',68,44.2,NULL,'2025-12-18 10:15:00',72.8,61.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),5,'user-sara','typescript','// islands attempt',        'Time Limit Exceeded',0,0,NULL,'2025-12-20 14:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),5,'user-sara','typescript','// islands dfs',            'Wrong Answer',0,0,NULL,'2025-12-21 09:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),5,'user-sara','typescript','// islands bfs correct',    'Accepted',85,45.8,NULL,'2025-12-22 08:30:00',65.4,52.3);

-- user-lily: Easy problems
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),6,'user-lily','typescript','// combine tables',          'Accepted',30,37.8,NULL,'2026-01-05 10:00:00',85.1,72.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),7,'user-lily','bash','// tenth line',               'Accepted',12,15.2,NULL,'2026-01-06 09:00:00',92.3,88.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-lily','javascript','// palindrome',               'Accepted',55,41.3,NULL,'2026-01-08 14:00:00',73.6,60.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-lily','typescript','// valid parentheses',       'Wrong Answer',0,0,NULL,'2026-01-10 11:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-lily','typescript','// stack based',            'Accepted',42,40.1,NULL,'2026-01-10 11:30:00',78.9,65.2);

-- user-max: Easy + a few Medium
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-max','javascript','// two-sum brute',         'Wrong Answer',0,0,NULL,'2026-01-10 08:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-max','javascript','// two-sum hash',           'Accepted',58,42.8,NULL,'2026-01-10 08:05:00',80.1,67.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-max','typescript','// reverse linked list',       'Accepted',38,39.5,NULL,'2026-01-12 16:00:00',71.2,58.9);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-max','typescript','// climbing stairs',         'Accepted',30,37.2,NULL,'2026-01-15 10:00:00',86.4,73.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-max','javascript','// max subarray brute',     'Wrong Answer',0,0,NULL,'2026-01-18 15:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-max','javascript','// kadane algorithm',        'Time Limit Exceeded',0,0,NULL,'2026-01-18 15:10:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-max','typescript','// inorder recursive',     'Accepted',45,41.0,NULL,'2026-01-20 09:00:00',77.3,62.1);

-- ============================================================================
-- INTERMEDIATE USERS (8 users, ~20 submissions each, Easy+Medium, ~60% pass)
-- user-alex, user-benq, user-david, user-kevin, user-scott, user-tom, u-001, u-002
-- ============================================================================

-- user-alex: Array/DP focused, NO Graph (for WEAK_POINT testing)
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-alex','javascript','// two-sum',                   'Accepted',52,43.2,NULL,'2025-11-20 10:00:00',80.5,68.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),2,'user-alex','typescript','// longest substring',          'Accepted',75,45.3,NULL,'2025-11-22 14:00:00',68.2,55.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),3,'user-alex','javascript','// merge intervals sort',       'Accepted',62,42.8,NULL,'2025-11-25 09:00:00',72.5,60.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-alex','typescript','// kadane',                     'Accepted',48,40.5,NULL,'2025-11-28 11:00:00',78.9,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),10,'user-alex','typescript','// product except self',        'Accepted',55,43.8,NULL,'2025-12-01 10:00:00',74.3,62.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-alex','typescript','// longest palindromic',       'Wrong Answer',0,0,NULL,'2025-12-03 15:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-alex','typescript','// dp approach',              'Accepted',95,46.2,NULL,'2025-12-03 15:30:00',62.8,51.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-alex','python','// climbing stairs',           'Accepted',25,36.8,NULL,'2025-12-05 08:00:00',88.6,75.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),22,'user-alex','typescript','// LIS dp O(n2)',             'Wrong Answer',0,0,NULL,'2025-12-08 16:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),22,'user-alex','typescript','// LIS dp',                  'Time Limit Exceeded',0,0,NULL,'2025-12-08 16:30:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),22,'user-alex','typescript','// LIS binary search',        'Accepted',110,44.5,NULL,'2025-12-10 11:00:00',55.3,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),23,'user-alex','java','// edit distance dp',           'Wrong Answer',0,0,NULL,'2025-12-15 14:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),23,'user-alex','java','// edit distance',            'Wrong Answer',0,0,NULL,'2025-12-16 10:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),11,'user-alex','javascript','// container water',           'Accepted',72,45.1,NULL,'2025-12-20 09:00:00',68.9,57.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-alex','typescript','// group anagrams',           'Accepted',65,44.3,NULL,'2025-12-22 10:00:00',71.5,59.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),17,'user-alex','javascript','// top k frequent',           'Accepted',58,43.5,NULL,'2025-12-25 08:00:00',76.2,64.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-alex','typescript','// binary search',             'Accepted',38,38.5,NULL,'2026-01-02 09:00:00',82.7,71.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),31,'user-alex','typescript','// rotated binary',             'Wrong Answer',0,0,NULL,'2026-01-05 14:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),31,'user-alex','typescript','// rotated binary search',      'Accepted',45,40.2,NULL,'2026-01-05 14:15:00',75.8,63.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-alex','javascript','// valid parentheses',         'Accepted',35,37.8,NULL,'2026-01-08 10:00:00',81.3,68.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),36,'user-alex','typescript','// jump game greedy',          'Accepted',48,41.2,NULL,'2026-01-10 16:00:00',70.6,58.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-alex','typescript','// reverse linked list',         'Accepted',32,38.9,NULL,'2026-01-12 08:00:00',84.2,72.6);

-- user-benq: Balanced Easy+Medium
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-benq','typescript','// two-sum hash',             'Accepted',45,42.1,NULL,'2025-11-15 12:00:00',85.2,73.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),4,'user-benq','typescript','// median binary search',      'Wrong Answer',0,0,NULL,'2025-11-18 09:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),4,'user-benq','typescript','// median binary search',      'Wrong Answer',0,0,NULL,'2025-11-18 09:30:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),4,'user-benq','typescript','// median correct',          'Accepted',88,48.5,NULL,'2025-11-18 10:00:00',52.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),5,'user-benq','typescript','// islands union find',        'Accepted',72,44.6,NULL,'2025-11-22 10:00:00',67.8,54.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-benq','typescript','// max subarray kadane',        'Accepted',42,39.8,NULL,'2025-11-25 08:00:00',80.4,68.9);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),11,'user-benq','typescript','// container water',           'Accepted',65,43.2,NULL,'2025-11-28 14:00:00',72.1,60.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-benq','javascript','// valid palindrome',          'Accepted',50,40.1,NULL,'2025-12-01 09:00:00',78.5,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-benq','typescript','// longest palindrome',        'Wrong Answer',0,0,NULL,'2025-12-05 11:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-benq','typescript','// longest palindrome dp',       'Accepted',88,45.8,NULL,'2025-12-05 11:30:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-benq','javascript','// climbing stairs',           'Accepted',22,36.5,NULL,'2025-12-08 15:00:00',90.1,76.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-benq','javascript','// inorder traversal',         'Accepted',40,41.3,NULL,'2025-12-10 08:00:00',75.4,62.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-benq','typescript','// binary search',              'Accepted',35,38.0,NULL,'2025-12-12 10:00:00',83.2,70.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-benq','typescript','// valid parens stack',         'Accepted',38,39.5,NULL,'2026-01-05 16:00:00',79.8,66.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),35,'user-benq','typescript','// min stack design',         'Accepted',55,42.8,NULL,'2026-01-10 09:00:00',71.3,58.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),36,'user-benq','javascript','// jump game',                'Wrong Answer',0,0,NULL,'2026-01-15 14:00:00',0,0);

-- user-david: DB + String focused
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),6,'user-david','typescript','// combine tables',           'Accepted',32,37.5,NULL,'2025-11-10 09:00:00',88.7,78.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),7,'user-david','bash','// tenth line sed',            'Accepted',8,15.0,NULL,'2025-11-12 08:00:00',95.0,90.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-david','javascript','// two-sum',                 'Accepted',58,42.6,NULL,'2025-11-15 14:00:00',76.9,65.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-david','typescript','// valid palindrome',          'Accepted',50,40.2,NULL,'2025-11-18 16:00:00',82.1,68.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-david','javascript','// group anagrams',           'Accepted',72,44.8,NULL,'2025-11-20 10:00:00',70.2,58.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),18,'user-david','typescript','// find anagrams',           'Wrong Answer',0,0,NULL,'2025-11-22 15:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),18,'user-david','typescript','// find anagrams sliding',   'Accepted',95,45.2,NULL,'2025-11-22 15:30:00',68.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),15,'user-david','typescript','// min window attempt',       'Wrong Answer',0,0,NULL,'2025-11-25 11:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),15,'user-david','typescript','// min window correct',      'Time Limit Exceeded',0,0,NULL,'2025-11-26 10:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-david','python','// climbing stairs',           'Accepted',28,36.2,NULL,'2025-12-01 08:00:00',87.3,74.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),25,'user-david','typescript','// level order bfs',          'Accepted',65,43.5,NULL,'2025-12-05 14:00:00',72.4,60.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-david','typescript','// binary search',              'Accepted',42,38.8,NULL,'2025-12-10 09:00:00',81.5,69.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-david','typescript','// reverse linked list',         'Accepted',34,39.2,NULL,'2026-01-05 10:00:00',83.8,71.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),34,'user-david','typescript','// daily temperatures',       'Accepted',75,44.1,NULL,'2026-01-08 08:00:00',68.7,56.3);

-- user-kevin: Heap + Sorting
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-kevin','typescript','// two-sum',                 'Accepted',50,41.8,NULL,'2025-11-18 10:00:00',82.5,70.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),3,'user-kevin','javascript','// merge intervals',          'Accepted',58,42.5,NULL,'2025-11-22 08:00:00',75.8,62.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-kevin','typescript','// max subarray',             'Accepted',45,40.2,NULL,'2025-12-01 14:00:00',78.2,65.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),17,'user-kevin','typescript','// top k heap',               'Accepted',62,43.5,NULL,'2025-12-05 09:00:00',73.6,61.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),17,'user-kevin','javascript','// top k sort',               'Wrong Answer',0,0,NULL,'2025-12-05 09:30:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),19,'user-kevin','typescript','// subarray sum k',            'Wrong Answer',0,0,NULL,'2025-12-08 11:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),19,'user-kevin','typescript','// subarray sum hash',         'Accepted',78,44.8,NULL,'2025-12-08 11:30:00',68.9,58.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-kevin','typescript','// binary search',             'Accepted',38,38.2,NULL,'2025-12-10 14:00:00',82.8,71.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),31,'user-kevin','typescript','// rotated search',             'Accepted',42,40.5,NULL,'2025-12-15 10:00:00',76.3,63.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),34,'user-kevin','typescript','// daily temps stack',         'Accepted',70,43.8,NULL,'2026-01-05 08:00:00',69.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),37,'user-kevin','javascript','// task scheduler',           'Wrong Answer',0,0,NULL,'2026-01-10 11:00:00',0,0);

-- user-scott: Tree + String
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-scott','typescript','// two-sum hash',             'Accepted',55,42.3,NULL,'2025-11-12 11:00:00',78.9,66.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-scott','javascript','// valid palindrome',          'Accepted',48,40.8,NULL,'2025-11-15 09:00:00',80.2,67.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-scott','typescript','// group anagrams',           'Accepted',60,43.5,NULL,'2025-11-18 14:00:00',74.1,61.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-scott','typescript','// inorder',                  'Accepted',40,41.5,NULL,'2025-11-20 08:00:00',76.8,62.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),25,'user-scott','typescript','// level order',              'Accepted',60,43.2,NULL,'2025-11-25 10:00:00',72.5,58.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-scott','java','// max path sum',             'Wrong Answer',0,0,NULL,'2025-12-01 09:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-scott','java','// max path sum',             'Wrong Answer',0,0,NULL,'2025-12-01 09:30:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-scott','java','// max path sum dfs',        'Time Limit Exceeded',0,0,NULL,'2025-12-01 10:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-scott','typescript','// binary search',             'Accepted',36,38.0,NULL,'2025-12-10 11:00:00',83.1,70.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-scott','typescript','// valid parens',             'Accepted',36,39.2,NULL,'2026-01-02 08:00:00',80.4,67.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),39,'user-scott','typescript','// powx-n',                   'Accepted',45,40.8,NULL,'2026-01-05 14:00:00',75.6,62.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-scott','typescript','// reverse list',               'Accepted',32,38.6,NULL,'2026-01-08 09:00:00',82.8,71.3);

-- user-tom: Array + Stack
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-tom','javascript','// two-sum',                   'Accepted',60,43.8,NULL,'2025-11-10 08:00:00',78.5,66.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),10,'user-tom','typescript','// product except self',        'Accepted',52,43.2,NULL,'2025-11-15 10:00:00',74.2,62.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),11,'user-tom','javascript','// container water',           'Wrong Answer',0,0,NULL,'2025-11-18 15:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),11,'user-tom','javascript','// container water 2p',       'Accepted',70,44.5,NULL,'2025-11-18 15:30:00',71.8,60.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),12,'user-tom','typescript','// trapping rain brute',       'Wrong Answer',0,0,NULL,'2025-11-22 10:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),12,'user-tom','typescript','// trapping rain 2p',         'Accepted',125,46.2,NULL,'2025-11-22 10:30:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-tom','javascript','// climbing stairs',           'Accepted',25,36.8,NULL,'2025-12-01 10:00:00',88.9,76.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-tom','typescript','// inorder',                  'Accepted',38,41.2,NULL,'2025-12-05 08:00:00',76.5,63.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-tom','typescript','// valid parens',             'Accepted',34,38.5,NULL,'2026-01-02 11:00:00',80.1,67.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),35,'user-tom','typescript','// min stack',                'Wrong Answer',0,0,NULL,'2026-01-05 09:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),35,'user-tom','typescript','// min stack impl',           'Accepted',58,42.8,NULL,'2026-01-05 09:30:00',72.5,59.6);

-- u-001: Basics
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'u-001','typescript','// two-sum',                   'Accepted',58,43.1,NULL,'2025-12-01 10:00:00',81.3,70.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),6,'u-001','typescript','// combine tables',            'Accepted',30,37.8,NULL,'2025-12-02 09:00:00',88.5,78.9);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'u-001','javascript','// max subarray',             'Wrong Answer',0,0,NULL,'2025-12-05 14:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'u-001','javascript','// kadane',                   'Accepted',50,40.5,NULL,'2025-12-05 14:10:00',78.6,65.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'u-001','typescript','// valid palindrome',           'Accepted',52,40.2,NULL,'2025-12-08 08:00:00',80.2,68.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'u-001','typescript','// group anagrams',           'Accepted',70,44.3,NULL,'2025-12-10 10:00:00',72.4,61.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'u-001','typescript','// climbing stairs',           'Accepted',28,36.5,NULL,'2025-12-12 14:00:00',86.8,74.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'u-001','typescript','// binary search',              'Accepted',40,38.5,NULL,'2025-12-15 09:00:00',82.5,71.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'u-001','typescript','// valid parens',             'Accepted',36,39.3,NULL,'2026-01-02 08:00:00',80.3,67.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'u-001','typescript','// reverse list',               'Accepted',34,39.1,NULL,'2026-01-05 10:00:00',84.1,72.5);

-- u-002: String + DP
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),2,'u-002','typescript','// longest substring',          'Accepted',80,45.3,NULL,'2025-12-01 11:00:00',68.2,55.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'u-002','typescript','// group anagrams',           'Accepted',62,43.8,NULL,'2025-12-03 10:00:00',72.5,60.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'u-002','typescript','// longest palindrome',        'Wrong Answer',0,0,NULL,'2025-12-05 14:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'u-002','typescript','// palindrome dp',               'Accepted',90,46.0,NULL,'2025-12-05 14:30:00',63.5,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),19,'u-002','javascript','// subarray sum',             'Accepted',75,44.5,NULL,'2025-12-08 09:00:00',70.2,58.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'u-002','typescript','// climbing stairs',           'Accepted',26,36.0,NULL,'2025-12-10 08:00:00',87.8,75.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'u-002','typescript','// valid parens',             'Accepted',38,39.2,NULL,'2026-01-02 09:00:00',80.5,67.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),35,'u-002','typescript','// min stack',                'Accepted',52,42.8,NULL,'2026-01-05 08:00:00',72.3,59.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),39,'u-002','typescript','// powx-n',                   'Wrong Answer',0,0,NULL,'2026-01-10 11:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),39,'u-002','typescript','// powx-n binary',           'Accepted',48,40.5,NULL,'2026-01-10 11:30:00',76.5,63.1);

-- ============================================================================
-- ADVANCED USERS (6 users, ~40 submissions each, all difficulties, ~75% pass)
-- user-chen, user-ecnerwala, user-jiangly, user-petr, user-tourist, user-um_nik
-- ============================================================================

-- user-chen: Balanced tags (for SIMILAR testing)
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-chen','typescript','// two-sum',                 'Accepted',48,42.5,NULL,'2025-10-20 08:00:00',82.5,70.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),2,'user-chen','typescript','// longest substring',          'Accepted',68,45.2,NULL,'2025-10-22 10:00:00',68.2,55.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),3,'user-chen','typescript','// merge intervals',          'Accepted',55,42.8,NULL,'2025-10-25 08:00:00',72.5,60.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),5,'user-chen','typescript','// islands dfs',              'Accepted',72,44.6,NULL,'2025-10-28 09:00:00',67.8,54.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-chen','typescript','// kadane',                   'Accepted',42,40.2,NULL,'2025-11-01 10:00:00',78.9,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),11,'user-chen','javascript','// container water',           'Accepted',68,43.2,NULL,'2025-11-03 14:00:00',72.1,60.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-chen','javascript','// valid palindrome',          'Accepted',48,40.1,NULL,'2025-11-05 09:00:00',78.5,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-chen','typescript','// group anagrams',           'Accepted',62,44.3,NULL,'2025-11-08 10:00:00',71.5,59.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-chen','typescript','// longest palindrome dp',       'Accepted',92,46.0,NULL,'2025-11-10 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-chen','python','// climbing stairs',           'Accepted',22,36.5,NULL,'2025-11-12 08:00:00',88.6,74.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),21,'user-chen','python','// coin change bfs',            'Accepted',95,48.2,NULL,'2025-11-15 14:00:00',62.8,51.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),22,'user-chen','typescript','// LIS binary search',        'Accepted',105,44.5,NULL,'2025-11-18 09:00:00',55.3,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-chen','typescript','// inorder traversal',         'Accepted',40,41.3,NULL,'2025-11-20 08:00:00',75.4,62.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),25,'user-chen','typescript','// level order bfs',            'Accepted',62,43.5,NULL,'2025-11-22 10:00:00',72.4,60.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),27,'user-chen','typescript','// clone graph dfs',            'Accepted',72,44.8,NULL,'2025-11-25 08:00:00',68.9,56.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),28,'user-chen','typescript','// course schedule dfs',         'Accepted',68,43.2,NULL,'2025-11-28 10:00:00',71.3,58.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-chen','typescript','// binary search',              'Accepted',38,38.0,NULL,'2025-12-01 09:00:00',82.8,71.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-chen','typescript','// valid parens',             'Accepted',36,39.5,NULL,'2026-01-02 08:00:00',79.8,66.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),34,'user-chen','typescript','// daily temps',              'Accepted',68,43.8,NULL,'2026-01-05 08:00:00',69.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),35,'user-chen','typescript','// min stack',                'Accepted',52,42.8,NULL,'2026-01-08 09:00:00',71.3,58.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),36,'user-chen','typescript','// jump game',                'Accepted',48,41.2,NULL,'2026-01-10 16:00:00',70.6,58.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),38,'user-chen','typescript','// candy greedy',             'Accepted',85,46.2,NULL,'2026-01-12 10:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-chen','typescript','// reverse list',               'Accepted',32,38.9,NULL,'2026-01-14 08:00:00',83.8,71.4);

-- user-ecnerwala: Heavy hitter, many problems
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-ecnerwala','typescript','// two-sum',                 'Accepted',45,41.8,NULL,'2025-10-15 08:00:00',85.2,73.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),2,'user-ecnerwala','typescript','// longest substring',          'Accepted',62,44.1,NULL,'2025-10-18 10:00:00',68.2,55.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),3,'user-ecnerwala','typescript','// merge intervals',          'Accepted',52,42.2,NULL,'2025-10-20 08:00:00',72.5,60.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),4,'user-ecnerwala','typescript','// median binary',            'Accepted',78,47.5,NULL,'2025-10-22 09:00:00',55.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),5,'user-ecnerwala','typescript','// islands bfs',              'Accepted',68,44.6,NULL,'2025-10-25 08:00:00',67.8,54.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-ecnerwala','typescript','// max subarray',             'Accepted',40,40.2,NULL,'2025-10-28 11:00:00',78.9,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),10,'user-ecnerwala','typescript','// product except self',        'Accepted',50,43.5,NULL,'2025-11-01 10:00:00',74.3,62.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),11,'user-ecnerwala','javascript','// container water',           'Accepted',62,43.2,NULL,'2025-11-03 14:00:00',72.1,60.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),12,'user-ecnerwala','typescript','// trapping rain',              'Accepted',115,46.2,NULL,'2025-11-05 10:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-ecnerwala','javascript','// palindrome',                'Accepted',45,40.1,NULL,'2025-11-08 09:00:00',78.5,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-ecnerwala','typescript','// group anagrams',           'Accepted',58,43.5,NULL,'2025-11-10 10:00:00',71.5,59.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),15,'user-ecnerwala','typescript','// min window',              'Accepted',88,45.2,NULL,'2025-11-12 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-ecnerwala','typescript','// longest palindrome',        'Accepted',85,46.0,NULL,'2025-11-15 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),17,'user-ecnerwala','javascript','// top k frequent',           'Accepted',55,43.5,NULL,'2025-11-18 09:00:00',73.6,61.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),18,'user-ecnerwala','typescript','// find anagrams',           'Accepted',90,45.2,NULL,'2025-11-20 14:00:00',68.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),19,'user-ecnerwala','typescript','// subarray sum k',            'Accepted',82,44.8,NULL,'2025-11-22 11:00:00',68.9,58.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-ecnerwala','javascript','// climbing stairs',           'Accepted',20,36.5,NULL,'2025-11-25 08:00:00',90.1,76.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),21,'user-ecnerwala','python','// coin change',                'Accepted',88,48.2,NULL,'2025-11-28 14:00:00',62.8,51.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),22,'user-ecnerwala','typescript','// LIS',                      'Accepted',98,44.5,NULL,'2025-12-01 09:00:00',55.3,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),23,'user-ecnerwala','java','// edit distance',               'Accepted',120,48.8,NULL,'2025-12-05 10:00:00',52.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-ecnerwala','typescript','// inorder',                  'Accepted',38,41.3,NULL,'2025-12-08 08:00:00',76.8,62.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),25,'user-ecnerwala','typescript','// level order',              'Accepted',58,43.2,NULL,'2025-12-10 08:00:00',72.4,60.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-ecnerwala','java','// max path sum',             'Accepted',75,46.5,NULL,'2025-12-12 09:00:00',62.1,51.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),27,'user-ecnerwala','typescript','// clone graph',              'Accepted',70,44.8,NULL,'2025-12-15 08:00:00',68.9,56.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),28,'user-ecnerwala','typescript','// course schedule',         'Accepted',65,43.2,NULL,'2025-12-18 10:00:00',71.3,58.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),29,'user-ecnerwala','java','// word ladder',               'Wrong Answer',0,0,NULL,'2025-12-22 14:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),29,'user-ecnerwala','java','// word ladder bfs',            'Accepted',180,48.5,NULL,'2025-12-22 14:30:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-ecnerwala','typescript','// binary search',             'Accepted',36,38.0,NULL,'2025-12-28 09:00:00',82.8,71.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),31,'user-ecnerwala','typescript','// rotated search',             'Accepted',42,40.5,NULL,'2026-01-05 14:00:00',76.3,63.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-ecnerwala','typescript','// valid parens',             'Accepted',34,39.5,NULL,'2026-01-08 10:00:00',80.4,67.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),34,'user-ecnerwala','typescript','// daily temps',              'Accepted',66,43.8,NULL,'2026-01-10 08:00:00',69.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),35,'user-ecnerwala','typescript','// min stack',                'Accepted',50,42.8,NULL,'2026-01-12 08:00:00',71.3,58.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),36,'user-ecnerwala','typescript','// jump game',                'Accepted',45,41.2,NULL,'2026-01-15 16:00:00',70.6,58.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),37,'user-ecnerwala','javascript','// task scheduler',           'Accepted',62,43.5,NULL,'2026-01-18 09:00:00',73.6,61.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),38,'user-ecnerwala','typescript','// candy',                   'Wrong Answer',0,0,NULL,'2026-01-20 10:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),38,'user-ecnerwala','typescript','// candy greedy 2',            'Accepted',90,46.2,NULL,'2026-01-20 10:30:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-ecnerwala','typescript','// reverse list',               'Accepted',30,38.9,NULL,'2026-01-22 08:00:00',83.8,71.4);

-- user-jiangly: Codeforces legend, high solve rate
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-jiangly','typescript','// two-sum',                 'Accepted',42,41.8,NULL,'2025-10-10 07:00:00',86.2,74.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),2,'user-jiangly','typescript','// longest substring',          'Accepted',58,44.1,NULL,'2025-10-12 09:00:00',68.2,55.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),3,'user-jiangly','typescript','// merge',                   'Accepted',50,42.2,NULL,'2025-10-15 08:00:00',72.5,60.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),4,'user-jiangly','typescript','// median',                   'Accepted',72,47.5,NULL,'2025-10-18 09:00:00',55.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),5,'user-jiangly','typescript','// islands',                   'Accepted',65,44.6,NULL,'2025-10-20 07:00:00',67.8,54.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-jiangly','typescript','// kadane',                   'Accepted',38,40.2,NULL,'2025-10-22 11:00:00',78.9,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),10,'user-jiangly','typescript','// product',                  'Accepted',48,43.5,NULL,'2025-10-25 10:00:00',74.3,62.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),11,'user-jiangly','typescript','// container',               'Accepted',62,43.2,NULL,'2025-11-01 14:00:00',72.1,60.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),12,'user-jiangly','typescript','// trapping rain',              'Accepted',108,46.2,NULL,'2025-11-03 10:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-jiangly','javascript','// palindrome',                'Accepted',42,40.1,NULL,'2025-11-05 09:00:00',78.5,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-jiangly','typescript','// anagrams',                 'Accepted',55,43.5,NULL,'2025-11-08 10:00:00',71.5,59.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),15,'user-jiangly','typescript','// min window',              'Accepted',82,45.2,NULL,'2025-11-10 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-jiangly','typescript','// palindrome dp',               'Accepted',88,46.0,NULL,'2025-11-12 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),17,'user-jiangly','javascript','// top k',                    'Accepted',52,43.5,NULL,'2025-11-15 09:00:00',73.6,61.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),18,'user-jiangly','typescript','// find anagrams',           'Accepted',88,45.2,NULL,'2025-11-18 14:00:00',68.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),19,'user-jiangly','typescript','// subarray sum',              'Accepted',80,44.8,NULL,'2025-11-20 11:00:00',70.2,58.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-jiangly','javascript','// stairs',                   'Accepted',18,36.5,NULL,'2025-11-25 08:00:00',90.1,76.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),21,'user-jiangly','python','// coin change',                'Accepted',82,48.2,NULL,'2025-11-28 14:00:00',62.8,51.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),22,'user-jiangly','typescript','// LIS',                      'Accepted',95,44.5,NULL,'2025-12-01 09:00:00',55.3,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),23,'user-jiangly','java','// edit distance',               'Accepted',110,48.8,NULL,'2025-12-05 10:00:00',52.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-jiangly','typescript','// inorder',                  'Accepted',38,41.3,NULL,'2025-12-08 08:00:00',76.8,62.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),25,'user-jiangly','typescript','// level order',              'Accepted',58,43.2,NULL,'2025-12-10 08:00:00',72.4,60.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-jiangly','java','// max path sum',             'Accepted',72,46.5,NULL,'2025-12-12 09:00:00',62.1,51.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),27,'user-jiangly','typescript','// clone graph',              'Accepted',68,44.8,NULL,'2025-12-15 08:00:00',68.9,56.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),28,'user-jiangly','typescript','// course schedule',         'Accepted',62,43.2,NULL,'2025-12-18 10:00:00',71.3,58.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),29,'user-jiangly','java','// word ladder',               'Accepted',175,48.5,NULL,'2025-12-22 14:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-jiangly','typescript','// binary search',             'Accepted',34,38.0,NULL,'2025-12-28 09:00:00',82.8,71.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),31,'user-jiangly','typescript','// rotated search',             'Accepted',40,40.5,NULL,'2026-01-05 14:00:00',76.3,63.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),32,'user-jiangly','typescript','// find min rotated',          'Accepted',38,40.5,NULL,'2026-01-06 09:00:00',82.5,71.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-jiangly','typescript','// valid parens',             'Accepted',32,39.5,NULL,'2026-01-08 10:00:00',80.4,67.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),34,'user-jiangly','typescript','// daily temps',              'Accepted',64,43.8,NULL,'2026-01-10 08:00:00',69.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),35,'user-jiangly','typescript','// min stack',                'Accepted',48,42.8,NULL,'2026-01-12 08:00:00',71.3,58.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),36,'user-jiangly','typescript','// jump game',                'Accepted',42,41.2,NULL,'2026-01-15 16:00:00',70.6,58.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),37,'user-jiangly','javascript','// task scheduler',           'Accepted',58,43.5,NULL,'2026-01-18 09:00:00',73.6,61.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),38,'user-jiangly','typescript','// candy',                   'Accepted',82,46.2,NULL,'2026-01-20 10:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-jiangly','typescript','// reverse list',               'Accepted',28,38.9,NULL,'2026-01-22 08:00:00',83.8,71.4);

-- user-petr: Graph + Hard
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),4,'user-petr','typescript','// median binary search',      'Accepted',82,47.5,NULL,'2025-10-20 09:00:00',55.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-petr','typescript','// kadane',                   'Accepted',40,40.2,NULL,'2025-10-25 08:00:00',78.9,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),12,'user-petr','typescript','// trapping rain',              'Accepted',110,46.2,NULL,'2025-11-05 10:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),15,'user-petr','typescript','// min window',              'Accepted',85,45.2,NULL,'2025-11-10 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-petr','typescript','// longest palindrome dp',       'Accepted',90,46.0,NULL,'2025-11-12 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-petr','javascript','// climbing stairs',           'Accepted',20,36.5,NULL,'2025-11-25 08:00:00',90.1,76.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),21,'user-petr','python','// coin change',                'Accepted',85,48.2,NULL,'2025-11-28 14:00:00',62.8,51.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),22,'user-petr','typescript','// LIS',                      'Accepted',100,44.5,NULL,'2025-12-01 09:00:00',55.3,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),23,'user-petr','java','// edit distance',               'Accepted',115,48.8,NULL,'2025-12-05 10:00:00',52.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-petr','java','// max path sum',             'Wrong Answer',0,0,NULL,'2025-12-12 09:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-petr','java','// max path sum 2',              'Accepted',80,46.5,NULL,'2025-12-12 09:30:00',62.1,51.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),27,'user-petr','typescript','// clone graph',              'Accepted',68,44.8,NULL,'2025-12-15 08:00:00',68.9,56.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),28,'user-petr','typescript','// course schedule',         'Accepted',65,43.2,NULL,'2025-12-18 10:00:00',71.3,58.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),29,'user-petr','java','// word ladder',               'Wrong Answer',0,0,NULL,'2025-12-22 14:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),29,'user-petr','java','// word ladder bfs',            'Accepted',170,48.5,NULL,'2025-12-22 14:30:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),32,'user-petr','typescript','// find min rotated',          'Accepted',38,40.5,NULL,'2026-01-06 09:00:00',82.5,71.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),34,'user-petr','typescript','// daily temps',              'Accepted',70,43.8,NULL,'2026-01-08 08:00:00',69.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),38,'user-petr','typescript','// candy',                   'Wrong Answer',0,0,NULL,'2026-01-20 10:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),38,'user-petr','typescript','// candy 2',                  'Accepted',88,46.2,NULL,'2026-01-20 10:30:00',58.2,48.6);

-- user-tourist: Legendary, high volume across ALL tags (for CHALLENGE testing)
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-tourist','cpp','// two-sum',                     'Accepted',40,41.8,NULL,'2025-10-08 06:00:00',86.2,74.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),2,'user-tourist','cpp','// longest substring',              'Accepted',55,44.1,NULL,'2025-10-10 10:00:00',68.2,55.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),3,'user-tourist','cpp','// merge intervals',             'Accepted',48,42.2,NULL,'2025-10-12 08:00:00',72.5,60.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),4,'user-tourist','cpp','// median',                   'Accepted',72,47.5,NULL,'2025-10-15 09:00:00',55.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),5,'user-tourist','cpp','// islands',                   'Accepted',62,44.6,NULL,'2025-10-18 07:00:00',67.8,54.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),6,'user-tourist','cpp','// combine tables',             'Accepted',25,36.4,NULL,'2025-10-20 06:00:00',90.5,78.9);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),7,'user-tourist','bash','// tenth line',               'Accepted',8,15.0,NULL,'2025-10-22 06:00:00',95.0,90.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-tourist','cpp','// kadane',                   'Accepted',38,40.2,NULL,'2025-10-25 11:00:00',78.9,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),10,'user-tourist','cpp','// product',                  'Accepted',48,43.5,NULL,'2025-10-28 10:00:00',74.3,62.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),11,'user-tourist','cpp','// container water',           'Accepted',60,43.2,NULL,'2025-11-01 14:00:00',72.1,60.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),12,'user-tourist','cpp','// trapping rain',              'Accepted',105,46.2,NULL,'2025-11-03 10:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-tourist','cpp','// palindrome',                'Accepted',42,40.1,NULL,'2025-11-05 09:00:00',78.5,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-tourist','cpp','// anagrams',                 'Accepted',55,43.5,NULL,'2025-11-08 10:00:00',71.5,59.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),15,'user-tourist','cpp','// min window',              'Accepted',80,45.2,NULL,'2025-11-10 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-tourist','cpp','// palindrome dp',               'Accepted',85,46.0,NULL,'2025-11-12 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),17,'user-tourist','cpp','// top k',                    'Accepted',50,43.5,NULL,'2025-11-15 09:00:00',73.6,61.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),18,'user-tourist','cpp','// find anagrams',           'Accepted',85,45.2,NULL,'2025-11-18 14:00:00',68.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),19,'user-tourist','cpp','// subarray sum',              'Accepted',78,44.8,NULL,'2025-11-20 11:00:00',70.2,58.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-tourist','cpp','// climbing stairs',           'Accepted',18,36.5,NULL,'2025-11-25 08:00:00',90.1,76.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),21,'user-tourist','python','// coin change',                'Accepted',80,48.2,NULL,'2025-11-28 14:00:00',62.8,51.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),22,'user-tourist','cpp','// LIS',                      'Accepted',92,44.5,NULL,'2025-12-01 09:00:00',55.3,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),23,'user-tourist','java','// edit distance',               'Accepted',108,48.8,NULL,'2025-12-05 10:00:00',52.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-tourist','cpp','// inorder',                  'Accepted',38,41.3,NULL,'2025-12-08 08:00:00',76.8,62.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),25,'user-tourist','cpp','// level order',              'Accepted',58,43.2,NULL,'2025-12-10 08:00:00',72.4,60.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-tourist','cpp','// max path sum',             'Accepted',70,46.5,NULL,'2025-12-12 09:00:00',62.1,51.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),27,'user-tourist','cpp','// clone graph',              'Accepted',65,44.8,NULL,'2025-12-15 08:00:00',68.9,56.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),28,'user-tourist','cpp','// course schedule',         'Accepted',60,43.2,NULL,'2025-12-18 10:00:00',71.3,58.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),29,'user-tourist','cpp','// word ladder',               'Accepted',165,48.5,NULL,'2025-12-22 14:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-tourist','cpp','// binary search',             'Accepted',34,38.0,NULL,'2025-12-28 09:00:00',82.8,71.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),31,'user-tourist','cpp','// rotated search',             'Accepted',40,40.5,NULL,'2026-01-05 14:00:00',76.3,63.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),32,'user-tourist','cpp','// find min rotated',          'Accepted',38,40.5,NULL,'2026-01-06 09:00:00',82.5,71.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-tourist','cpp','// valid parens',             'Accepted',32,39.5,NULL,'2026-01-08 10:00:00',80.4,67.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),34,'user-tourist','cpp','// daily temps',              'Accepted',62,43.8,NULL,'2026-01-10 08:00:00',69.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),35,'user-tourist','cpp','// min stack',                'Accepted',48,42.8,NULL,'2026-01-12 08:00:00',71.3,58.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),36,'user-tourist','cpp','// jump game',                'Accepted',42,41.2,NULL,'2026-01-15 16:00:00',70.6,58.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),37,'user-tourist','cpp','// task scheduler',           'Accepted',58,43.5,NULL,'2026-01-18 09:00:00',73.6,61.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),38,'user-tourist','cpp','// candy',                   'Wrong Answer',0,0,NULL,'2026-01-20 10:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),38,'user-tourist','cpp','// candy 2',                  'Accepted',85,46.2,NULL,'2026-01-20 10:30:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),39,'user-tourist','cpp','// powx-n',                   'Accepted',42,40.8,NULL,'2026-01-22 08:00:00',75.6,62.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-tourist','cpp','// reverse list',               'Accepted',28,38.9,NULL,'2026-01-22 08:00:00',83.8,71.4);

-- user-um_nik: CF strategy overlap with tourist
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),1,'user-um_nik','cpp','// two-sum',                 'Accepted',48,41.8,NULL,'2025-10-10 06:00:00',86.2,74.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),3,'user-um_nik','cpp','// merge',                   'Accepted',52,42.2,NULL,'2025-10-15 08:00:00',72.5,60.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),4,'user-um_nik','cpp','// median',                   'Wrong Answer',0,0,NULL,'2025-10-18 09:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),4,'user-um_nik','cpp','// median 2',                  'Accepted',75,47.5,NULL,'2025-10-18 09:30:00',55.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),5,'user-um_nik','cpp','// islands',                   'Accepted',60,44.6,NULL,'2025-10-20 07:00:00',67.8,54.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),9,'user-um_nik','cpp','// kadane',                   'Accepted',38,40.2,NULL,'2025-10-25 11:00:00',78.9,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),11,'user-um_nik','cpp','// container',               'Accepted',60,43.2,NULL,'2025-11-01 14:00:00',72.1,60.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-um_nik','cpp','// palindrome',                'Wrong Answer',0,0,NULL,'2025-11-05 09:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),13,'user-um_nik','cpp','// palindrome 2',              'Accepted',48,40.1,NULL,'2025-11-05 09:10:00',78.5,65.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),14,'user-um_nik','cpp','// anagrams',                 'Accepted',60,43.5,NULL,'2025-11-08 10:00:00',71.5,59.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),15,'user-um_nik','cpp','// min window',              'Accepted',78,45.2,NULL,'2025-11-10 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),16,'user-um_nik','cpp','// palindrome dp',               'Accepted',82,46.0,NULL,'2025-11-12 11:00:00',65.2,52.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),20,'user-um_nik','cpp','// stairs',                   'Accepted',20,36.5,NULL,'2025-11-25 08:00:00',90.1,76.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),21,'user-um_nik','python','// coin change',                'Wrong Answer',0,0,NULL,'2025-11-28 14:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),21,'user-um_nik','python','// coin change 2',              'Accepted',82,48.2,NULL,'2025-11-28 14:30:00',62.8,51.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),22,'user-um_nik','cpp','// LIS',                      'Accepted',98,44.5,NULL,'2025-12-01 09:00:00',55.3,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),23,'user-um_nik','java','// edit distance',               'Wrong Answer',0,0,NULL,'2025-12-05 10:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),23,'user-um_nik','java','// edit distance 2',            'Accepted',110,48.8,NULL,'2025-12-05 10:30:00',52.1,42.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),24,'user-um_nik','cpp','// inorder',                  'Accepted',38,41.3,NULL,'2025-12-08 08:00:00',76.8,62.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),25,'user-um_nik','cpp','// level order',              'Accepted',58,43.2,NULL,'2025-12-10 08:00:00',72.4,60.1);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-um_nik','cpp','// max path sum',             'Wrong Answer',0,0,NULL,'2025-12-12 09:00:00',0,0);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),26,'user-um_nik','cpp','// max path 2',              'Accepted',80,46.5,NULL,'2025-12-12 09:30:00',62.1,51.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),27,'user-um_nik','cpp','// clone graph',              'Accepted',65,44.8,NULL,'2025-12-15 08:00:00',68.9,56.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),28,'user-um_nik','cpp','// course schedule',         'Accepted',62,43.2,NULL,'2025-12-18 10:00:00',71.3,58.7);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),29,'user-um_nik','cpp','// word ladder',               'Accepted',160,48.5,NULL,'2025-12-22 14:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),30,'user-um_nik','cpp','// binary search',             'Accepted',34,38.0,NULL,'2025-12-28 09:00:00',82.8,71.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),31,'user-um_nik','cpp','// rotated search',             'Accepted',40,40.5,NULL,'2026-01-05 14:00:00',76.3,63.8);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),32,'user-um_nik','cpp','// find min rotated',          'Accepted',38,40.5,NULL,'2026-01-06 09:00:00',82.5,71.3);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),33,'user-um_nik','cpp','// valid parens',             'Accepted',32,39.5,NULL,'2026-01-08 10:00:00',80.4,67.5);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),34,'user-um_nik','cpp','// daily temps',              'Accepted',62,43.8,NULL,'2026-01-10 08:00:00',69.5,57.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),35,'user-um_nik','cpp','// min stack',                'Accepted',48,42.8,NULL,'2026-01-12 08:00:00',71.3,58.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),36,'user-um_nik','cpp','// jump game',                'Accepted',42,41.2,NULL,'2026-01-15 16:00:00',70.6,58.2);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),38,'user-um_nik','cpp','// candy',                   'Accepted',82,46.2,NULL,'2026-01-20 10:00:00',58.2,48.6);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),39,'user-um_nik','cpp','// powx-n',                   'Accepted',42,40.8,NULL,'2026-01-22 08:00:00',75.6,62.4);
INSERT INTO `submissions` (`id`,`problem_id`,`user_id`,`language`,`code`,`status`,`runtime`,`memory`,`notes`,`created_at`,`runtime_percentile`,`memory_percentile`) VALUES (UUID(),40,'user-um_nik','cpp','// reverse list',               'Accepted',28,38.9,NULL,'2026-01-22 08:00:00',83.8,71.4);

SET FOREIGN_KEY_CHECKS=1;
