#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/.env"
FORCE=false

usage() {
  cat <<'EOF'
Usage: ./scripts/dev/init-env.sh [--output PATH] [--force]

Generates a private local development environment. Infrastructure credentials are
random; the documented application login is fixed for developer convenience.
Existing files are preserved unless --force is supplied.
EOF
}

while (($#)); do
  case "$1" in
    --output)
      OUTPUT_FILE="${2:?--output requires a path}"
      shift 2
      ;;
    --force)
      FORCE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -e "$OUTPUT_FILE" && "$FORCE" != true ]]; then
  echo "Environment already exists: $OUTPUT_FILE"
  echo "Leaving it unchanged. Use --force only for a disposable environment."
  exit 0
fi

for command in openssl; do
  command -v "$command" >/dev/null 2>&1 || {
    echo "Required command not found: $command" >&2
    exit 1
  }
done

random_hex() {
  openssl rand -hex "$1"
}

random_base64() {
  openssl rand -base64 "$1" | tr -d '\r\n'
}

db_password="db_$(random_hex 18)"
mysql_root_password="root_$(random_hex 20)"
redis_password="redis_$(random_hex 18)"
jwt_secret="$(random_hex 48)"
nacos_password="Nacos!$(random_hex 18)"
nacos_auth_token="$(random_base64 48)"
nacos_identity_key="dev_$(random_hex 12)"
nacos_identity_value="$(random_hex 24)"
meili_master_key="meili_$(random_base64 32)"
auth_db_password="auth_$(random_hex 18)"
admin_db_password="admin_$(random_hex 18)"
app_db_password="app_$(random_hex 18)"
notification_db_password="notification_$(random_hex 18)"
submission_db_password="submission_$(random_hex 18)"
submission_migration_password="migration_submission_$(random_hex 24)"

mkdir -p "$(dirname "$OUTPUT_FILE")"
umask 077

cat >"$OUTPUT_FILE" <<EOF
# Generated by scripts/dev/init-env.sh. Local development only.
# Do not commit this file or reuse these credentials outside this checkout.

SPRING_PROFILES_ACTIVE=dev
# Direct backend-app fallback; PM2/Compose override each owner to 9101/9102/9103.
SERVER_PORT=9103
CONSOLE_PORT=9002
MANAGEMENT_PORT=9003

DB_HOST=localhost
DB_PORT=23306
DB_USER=ulticode
DB_PASSWORD="$db_password"
DB_NAME=ulticode

# Owner runtime schemas/accounts. All owners share one MySQL instance but
# runtime accounts are limited to their own schema.
AUTH_DB_HOST=localhost
AUTH_DB_PORT=23306
AUTH_DB_NAME=auth
AUTH_DB_USER=auth_rw
AUTH_DB_PASSWORD="$auth_db_password"
ADMIN_DB_HOST=localhost
ADMIN_DB_PORT=23306
ADMIN_DB_NAME=admin
ADMIN_DB_USER=admin_rw
ADMIN_DB_PASSWORD="$admin_db_password"
APP_DB_HOST=localhost
APP_DB_PORT=23306
APP_DB_NAME=app
APP_DB_USER=app_rw
APP_DB_PASSWORD="$app_db_password"
NOTIFICATION_DB_HOST=localhost
NOTIFICATION_DB_PORT=23306
NOTIFICATION_DB_NAME=notification
NOTIFICATION_DB_USER=notification_rw
NOTIFICATION_DB_PASSWORD="$notification_db_password"

# The local PM2 stack provisions all five Owner accounts from this file. The
# direct Submission route remains cutover-gated; dev-lite forces the local
# compatibility route and dev-full requires the explicit cutover flag.
SUBMISSION_DB_HOST=localhost
SUBMISSION_DB_PORT=23306
SUBMISSION_DB_NAME=submission
SUBMISSION_DB_USER=submission_rw
SUBMISSION_DB_PASSWORD="$submission_db_password"
SUBMISSION_MIGRATION_DB_USER=migration_submission
SUBMISSION_MIGRATION_DB_PASSWORD="$submission_migration_password"
APP_SUBMISSION_ROUTING_MODE=local
# Exact App runtime account used by the submission cutover grant gate.
SUBMISSION_APP_DB_USER=app_rw
SUBMISSION_APP_DB_HOST=%
MIGRATION_MYSQL_CONTAINER=ulticode-mysql
MIGRATION_MYSQL_CONTAINER_PORT=3306
DEV_LOCAL_OWNER_BASELINE=true
SUBMISSION_CUTOVER_COMPLETE=false
MYSQL_ROOT_PASSWORD="$mysql_root_password"
DB_ROOT_PASSWORD="$mysql_root_password"

REDIS_HOST=localhost
REDIS_PORT=26379
REDIS_PASSWORD="$redis_password"
REDIS_DB=0

JWT_SECRET="$jwt_secret"
JWT_COOKIE_SECURE=false
CORS_ALLOWED_ORIGINS=http://localhost:9002,http://localhost:9003,http://127.0.0.1:9002,http://127.0.0.1:9003
FRONTEND_URL=http://localhost:9002

NACOS_SERVER_ADDR=localhost:28848
NACOS_HOST=localhost
NACOS_PORT=28848
NACOS_GRPC_PORT=29848
NACOS_NAMESPACE=public
NACOS_GROUP=DEFAULT_GROUP
NACOS_USERNAME=ulticode_dev_admin
NACOS_PASSWORD="$nacos_password"
NACOS_AUTH_TOKEN="$nacos_auth_token"
NACOS_AUTH_IDENTITY_KEY="$nacos_identity_key"
NACOS_AUTH_IDENTITY_VALUE="$nacos_identity_value"

SPRINGDOC_ENABLED=true
MEILISEARCH_ENABLED=false
MEILI_MASTER_KEY="$meili_master_key"
# Sandbox (D-form) — image must be built locally, see
# CLAUDE.md § Sandbox Harness. Under local PM2 SANDBOX_ENABLED has NO effect
# on execution (the executor keys off sandbox.executor, default docker); it is
# a historical placeholder, keep false. The production compose Judge Worker
# forwards every SANDBOX_* variable and defaults SANDBOX_ENABLED=true, so on
# the deployment host these are live tuning knobs. SANDBOX_SECCOMP_PROFILE is
# a repository-root-relative path (no ../). The backend re-roots it by walking
# up from the JVM working directory, so it resolves identically under mvn
# spring-boot:run, a packaged jar, and PM2 — a ../ prefix here silently broke
# every judge call with a masked "Runtime Error" because the JVM cwd drifts
# per launch mode.
SANDBOX_ENABLED=false
SANDBOX_IMAGE=ulticode-sandbox:latest
SANDBOX_MEMORY=256m
SANDBOX_CPUS=1.0
SANDBOX_TIMEOUT=10
SANDBOX_PIDS_LIMIT=128
SANDBOX_SECCOMP_PROFILE=docker/sandbox/seccomp-profile.json
# Production Compose Judge Worker only; local PM2 uses the repository-relative
# seccomp path above. Set these in the deployment host's .env when applicable.
SANDBOX_HOST_DIR=/opt/ulticode/sandbox
# Production Compose Judge Worker only: compose prepends the -Djava.io.tmpdir
# redirect to this value. Leave empty unless you need extra JVM flags.
JAVA_TOOL_OPTIONS=
DOCKER_GID=999
# Repository-relative backup directory; deployment environments may override
# BACKUP_DIR with their own relative mount point.
BACKUP_DIR=.local/backups
AUDIT_EXPORT_LIMIT=10000

APP_BOOTSTRAP_ADMIN_ENABLED=false
APP_BOOTSTRAP_ADMIN_USERNAME=
APP_BOOTSTRAP_ADMIN_EMAIL=
APP_BOOTSTRAP_ADMIN_PASSWORD=

# Fixed credentials for the disposable local development database only.
DEV_SEED_USERS_ENABLED=true
DEV_SEED_DATA_ENABLED=true
DEV_SEED_ADMIN_USERNAME=admin
DEV_SEED_ADMIN_EMAIL=admin@localhost.test
DEV_SEED_ADMIN_PASSWORD=admin123
DEV_SEED_ADMIN_ROLE=ADMIN

GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GITHUB_REDIRECT_URI=http://localhost:9002/api/auth/github/callback
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=http://localhost:9002/api/auth/google/callback
SMTP_HOST=localhost
SMTP_PORT=1025
SMTP_USER=
SMTP_PASSWORD=
EMAIL_ENABLED=false
EMAIL_FROM_NAME="UltiCode Dev"

VITE_API_BASE_URL=/api
VITE_ADMIN_BASE_URL=http://localhost:9003
VITE_TEST_USERNAME=admin
VITE_TEST_PASSWORD=admin123
EOF

chmod 600 "$OUTPUT_FILE"
echo "Generated private development environment: $OUTPUT_FILE"
echo "Run ./scripts/dev/up.sh to start the project."
