#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/.env"
FORCE=false

usage() {
  cat <<'EOF'
Usage: ./scripts/dev/init-env.sh [--output PATH] [--force]

Generates a private local development environment. Infrastructure credentials are
random; the documented application login is fixed for developer convenience.
Existing files are preserved unless --force is supplied.
EOF
}

while (($#)); do
  case "$1" in
    --output)
      OUTPUT_FILE="${2:?--output requires a path}"
      shift 2
      ;;
    --force)
      FORCE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -e "$OUTPUT_FILE" && "$FORCE" != true ]]; then
  echo "Environment already exists: $OUTPUT_FILE"
  echo "Leaving it unchanged. Use --force only for a disposable environment."
  exit 0
fi

for command in openssl base64 sha256sum; do
  command -v "$command" >/dev/null 2>&1 || {
    echo "Required command not found: $command" >&2
    exit 1
  }
done

random_hex() {
  openssl rand -hex "$1"
}

random_base64() {
  openssl rand -base64 "$1" | tr -d '\r\n'
}

rsa_private_key() {
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null \
    | openssl pkcs8 -topk8 -nocrypt -outform DER 2>/dev/null \
    | base64 -w0
}

rsa_public_key() {
  printf '%s' "$1" | base64 -d \
    | openssl pkey -inform DER -pubout -outform DER 2>/dev/null \
    | base64 -w0
}

rsa_key_id() {
  printf '%s' "$1" | base64 -d | sha256sum | cut -c1-16
}

db_password="db_$(random_hex 18)"
mysql_root_password="root_$(random_hex 20)"
auth_redis_password="auth_redis_$(random_hex 18)"
admin_redis_password="admin_redis_$(random_hex 18)"
app_redis_password="app_redis_$(random_hex 18)"
submission_redis_password="submission_redis_$(random_hex 18)"
search_redis_password="search_redis_$(random_hex 18)"
notification_redis_password="notification_redis_$(random_hex 18)"
judge_redis_password="judge_redis_$(random_hex 18)"
ops_redis_password="ops_redis_$(random_hex 18)"
health_redis_password="health_redis_$(random_hex 18)"
redis_replication_password="redis_replication_$(random_hex 18)"
redis_sentinel_password="redis_sentinel_$(random_hex 18)"
jwt_secret="$(random_hex 48)"
nacos_password="Nacos!$(random_hex 18)"
nacos_auth_token="$(random_base64 48)"
nacos_identity_key="dev_$(random_hex 12)"
nacos_identity_value="$(random_hex 24)"
auth_nacos_password="auth_nacos_$(random_hex 18)"
admin_nacos_password="admin_nacos_$(random_hex 18)"
app_nacos_password="app_nacos_$(random_hex 18)"
submission_nacos_password="submission_nacos_$(random_hex 18)"
notification_nacos_password="notification_nacos_$(random_hex 18)"
judge_nacos_password="judge_nacos_$(random_hex 18)"
internal_delegation_private_key="$(rsa_private_key)"
internal_delegation_public_key="$(rsa_public_key "$internal_delegation_private_key")"
internal_delegation_key_id="$(rsa_key_id "$internal_delegation_public_key")"
bootstrap_delegation_private_key="$(rsa_private_key)"
bootstrap_delegation_public_key="$(rsa_public_key "$bootstrap_delegation_private_key")"
bootstrap_delegation_key_id="$(rsa_key_id "$bootstrap_delegation_public_key")"
nacos_db_password="nacos_db_$(random_hex 24)"
meili_master_key="meili_$(random_base64 32)"
auth_db_password="auth_$(random_hex 18)"
admin_db_password="admin_$(random_hex 18)"
app_db_password="app_$(random_hex 18)"
notification_db_password="notification_$(random_hex 18)"
submission_db_password="submission_$(random_hex 18)"
submission_migration_password="migration_submission_$(random_hex 24)"

mkdir -p "$(dirname "$OUTPUT_FILE")"
umask 077

cat >"$OUTPUT_FILE" <<EOF
# Generated by scripts/dev/init-env.sh. Local development only.
# Do not commit this file or reuse these credentials outside this checkout.

SPRING_PROFILES_ACTIVE=dev
# Direct backend-app fallback; PM2/Compose override each owner to 9101/9102/9103.
SERVER_PORT=9103
CONSOLE_PORT=9002
MANAGEMENT_PORT=9003

DB_HOST=localhost
DB_PORT=23306
DB_USER=ulticode
DB_PASSWORD="$db_password"
DB_NAME=ulticode

# Owner runtime schemas/accounts. All owners share one MySQL instance but
# runtime accounts are limited to their own schema.
AUTH_DB_HOST=localhost
AUTH_DB_PORT=23306
AUTH_DB_NAME=auth
AUTH_DB_USER=auth_rw
AUTH_DB_PASSWORD="$auth_db_password"
ADMIN_DB_HOST=localhost
ADMIN_DB_PORT=23306
ADMIN_DB_NAME=admin
ADMIN_DB_USER=admin_rw
ADMIN_DB_PASSWORD="$admin_db_password"
APP_DB_HOST=localhost
APP_DB_PORT=23306
APP_DB_NAME=app
APP_DB_USER=app_rw
APP_DB_PASSWORD="$app_db_password"
NOTIFICATION_DB_HOST=localhost
NOTIFICATION_DB_PORT=23306
NOTIFICATION_DB_NAME=notification
NOTIFICATION_DB_USER=notification_rw
NOTIFICATION_DB_PASSWORD="$notification_db_password"

# The local PM2 stack provisions all five Owner accounts from this file. Current
# modes always use the remote Submission owner route and require the completed
# data/grant cutover marker; this generator never emits a local compatibility
# route.
SUBMISSION_DB_HOST=localhost
SUBMISSION_DB_PORT=23306
SUBMISSION_DB_NAME=submission
SUBMISSION_DB_USER=submission_rw
SUBMISSION_DB_PASSWORD="$submission_db_password"
SUBMISSION_MIGRATION_DB_USER=migration_submission
SUBMISSION_MIGRATION_DB_PASSWORD="$submission_migration_password"
APP_SUBMISSION_ROUTING_MODE=remote
# Exact App runtime account used by the submission cutover grant gate.
SUBMISSION_APP_DB_USER=app_rw
SUBMISSION_APP_DB_HOST=%
MIGRATION_MYSQL_CONTAINER_PORT=3306
DEV_LOCAL_OWNER_BASELINE=true
SUBMISSION_CUTOVER_COMPLETE=false
MYSQL_ROOT_PASSWORD="$mysql_root_password"
DB_ROOT_PASSWORD="$mysql_root_password"

REDIS_HOST=localhost
REDIS_PORT=26379
REDIS_DB=0
REDIS_ACL_DIR=.local/redis

# Per-owner Redis ACL credentials (review 2026-08-25). The runtime ACL is
# re-rendered outside the repository from these values below.
AUTH_REDIS_PASSWORD="$auth_redis_password"
ADMIN_REDIS_PASSWORD="$admin_redis_password"
APP_REDIS_PASSWORD="$app_redis_password"
SUBMISSION_REDIS_PASSWORD="$submission_redis_password"
SEARCH_REDIS_PASSWORD="$search_redis_password"
NOTIFICATION_REDIS_PASSWORD="$notification_redis_password"
JUDGE_REDIS_PASSWORD="$judge_redis_password"
OPS_REDIS_PASSWORD="$ops_redis_password"
HEALTH_REDIS_PASSWORD="$health_redis_password"
REDIS_REPLICATION_PASSWORD="$redis_replication_password"
REDIS_SENTINEL_PASSWORD="$redis_sentinel_password"

JWT_SECRET="$jwt_secret"
INTERNAL_DELEGATION_PRIVATE_KEY="$internal_delegation_private_key"
INTERNAL_DELEGATION_PUBLIC_KEY="$internal_delegation_public_key"
INTERNAL_DELEGATION_KEY_ID="$internal_delegation_key_id"
BOOTSTRAP_DELEGATION_PRIVATE_KEY="$bootstrap_delegation_private_key"
BOOTSTRAP_DELEGATION_PUBLIC_KEY="$bootstrap_delegation_public_key"
BOOTSTRAP_DELEGATION_KEY_ID="$bootstrap_delegation_key_id"
JWT_COOKIE_SECURE=false
CORS_ALLOWED_ORIGINS=http://localhost:9002,http://localhost:9003,http://127.0.0.1:9002,http://127.0.0.1:9003
FRONTEND_URL=http://localhost:9002

NACOS_SERVER_ADDR=localhost:28848
NACOS_HOST=localhost
NACOS_PORT=28848
NACOS_GRPC_PORT=29848
NACOS_NAMESPACE=dev
NACOS_GROUP=DEFAULT_GROUP
DUBBO_NAMESPACE=dev
NACOS_USERNAME=ulticode_dev_admin
NACOS_PASSWORD="$nacos_password"
AUTH_NACOS_USERNAME=ulticode-auth
AUTH_NACOS_PASSWORD="$auth_nacos_password"
ADMIN_NACOS_USERNAME=ulticode-admin
ADMIN_NACOS_PASSWORD="$admin_nacos_password"
APP_NACOS_USERNAME=ulticode-app
APP_NACOS_PASSWORD="$app_nacos_password"
SUBMISSION_NACOS_USERNAME=ulticode-submission
SUBMISSION_NACOS_PASSWORD="$submission_nacos_password"
NOTIFICATION_NACOS_USERNAME=ulticode-notification
NOTIFICATION_NACOS_PASSWORD="$notification_nacos_password"
JUDGE_NACOS_USERNAME=ulticode-judge
JUDGE_NACOS_PASSWORD="$judge_nacos_password"
NACOS_AUTH_TOKEN="$nacos_auth_token"
NACOS_AUTH_IDENTITY_KEY="$nacos_identity_key"
NACOS_AUTH_IDENTITY_VALUE="$nacos_identity_value"
NACOS_DB_USER=nacos_rw
NACOS_DB_PASSWORD="$nacos_db_password"

SPRINGDOC_ENABLED=true
MEILISEARCH_ENABLED=false
MEILI_MASTER_KEY="$meili_master_key"
# Production only: set an operator-managed collector reachable from the
# deployment Compose network before running production Compose. Deliberately
# left unset — production Compose fails closed on an unset or empty value;
# local development falls back to localhost:4318.
#MANAGEMENT_OTLP_TRACING_ENDPOINT=http://otel-collector:4318/v1/traces
# Sandbox (D-form) — image must be built locally, see
# CLAUDE.md § Sandbox Harness. Under local PM2 SANDBOX_ENABLED has NO effect
# on execution (the executor keys off sandbox.executor, default docker); it is
# a historical placeholder, keep false. The production compose Judge Worker
# forwards every SANDBOX_* variable and defaults SANDBOX_ENABLED=true, so on
# the deployment host these are live tuning knobs. SANDBOX_SECCOMP_PROFILE is
# a repository-root-relative path (no ../). The backend re-roots it by walking
# up from the JVM working directory, so it resolves identically under mvn
# spring-boot:run, a packaged jar, and PM2 — a ../ prefix here silently broke
# every judge call with a masked "Runtime Error" because the JVM cwd drifts
# per launch mode.
SANDBOX_ENABLED=false
SANDBOX_IMAGE=ulticode-sandbox:latest
SANDBOX_MEMORY=256m
SANDBOX_CPUS=1.0
SANDBOX_TIMEOUT=10
SANDBOX_PIDS_LIMIT=128
SANDBOX_SECCOMP_PROFILE=docker/sandbox/seccomp-profile.json
# Production Compose Judge Worker only: production uses a dedicated remote
# rootless Docker daemon over TLS. Supply JUDGE_DOCKER_HOST and
# JUDGE_DOCKER_CERT_DIR from the deployment secret/config store; init-env
# deliberately does not generate or persist them.
# Development-only socket profile uses this
# local group id; production Compose never consumes it.
SANDBOX_HOST_DIR=/opt/ulticode/sandbox
JAVA_TOOL_OPTIONS=
DOCKER_GID=999
# Repository-relative backup directory; deployment environments may override
# BACKUP_DIR with their own relative mount point.
BACKUP_DIR=.local/backups
AUDIT_EXPORT_LIMIT=10000

APP_BOOTSTRAP_ADMIN_ENABLED=false
APP_BOOTSTRAP_ADMIN_USERNAME=
APP_BOOTSTRAP_ADMIN_EMAIL=
APP_BOOTSTRAP_ADMIN_PASSWORD=

# Fixed credentials for the disposable local development database only.
DEV_SEED_USERS_ENABLED=true
DEV_SEED_DATA_ENABLED=true
DEV_SEED_ADMIN_USERNAME=admin
DEV_SEED_ADMIN_EMAIL=admin@localhost.test
DEV_SEED_ADMIN_PASSWORD=admin123
DEV_SEED_ADMIN_ROLE=ADMIN

GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GITHUB_REDIRECT_URI=http://localhost:9002/api/auth/github/callback
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=http://localhost:9002/api/auth/google/callback
SMTP_HOST=localhost
SMTP_PORT=1025
SMTP_USER=
SMTP_PASSWORD=
EMAIL_ENABLED=false
EMAIL_FROM_NAME="UltiCode Dev"

VITE_API_BASE_URL=/api
VITE_ADMIN_BASE_URL=http://localhost:9003
VITE_TEST_USERNAME=admin
VITE_TEST_PASSWORD=admin123
EOF

chmod 600 "$OUTPUT_FILE"

# Re-render the runtime Redis ACL file from the freshly generated per-owner
# passwords so the dev stack always pairs with this .env. The output stays
# outside the tracked repository (review 2026-08-25 / P2-REDIS-001).
ACL_DIR="${REDIS_ACL_DIR:-$ROOT_DIR/.local/redis}"
ACL_FILE="${REDIS_ACL_FILE:-$ACL_DIR/users.acl}"
[[ "$ACL_DIR" == /* ]] || ACL_DIR="$ROOT_DIR/$ACL_DIR"
[[ "$ACL_FILE" == /* ]] || ACL_FILE="$ROOT_DIR/$ACL_FILE"
mkdir -p "$ACL_DIR"
chmod 755 "$ACL_DIR"
if [[ -f "$ROOT_DIR/docker/redis/generate-users-acl.sh" ]]; then
  # shellcheck disable=SC1090
  set -a
  source "$OUTPUT_FILE"
  set +a
  "$ROOT_DIR/docker/redis/generate-users-acl.sh" "$ACL_FILE"
  echo "Materialized Redis ACL file: $ACL_FILE"
else
  echo "WARNING: docker/redis/generate-users-acl.sh not found; runtime Redis ACL was not materialized." >&2
fi

echo "Generated private development environment: $OUTPUT_FILE"
echo "Run ./scripts/dev/up.sh to start the project."
